apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    otel:
      endpointAddress: "otel-lgtm:4317"
      isSecure: false
      protocol: grpc
