# Docker compose for postgres and MUnique OpenMU
version: '3'

services:
  # Deploy MUnique OpenMU from docker hub
  munique:
    image: munique/openmu
    container_name: munique
    restart: unless-stopped
    tty: true
    ports:
      - "1234:1234"
      - "55901:55901"
      - "55902:55902"
      - "55903:55903"
      - "44405:44405"
      - "55980:55980"
    environment:
      SERVICE_NAME: munique
      SERVICE_TAGS: dev
      DB_HOST: database
    working_dir: /app/
    links:
      - database
    networks:
      - munique-network
    depends_on:
      - database

  # Deploy postgres database from docker hub
  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openmu
      POSTGRES_USER: postgres
    networks:
      - munique-network

networks:
  munique-network:
    driver: bridge

volumes:
  dbdata:
    driver: local