# Build and Push Docker Container

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
    - tests/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'set-projectVersion.ps1'
- bash: |
    #!/bin/sh
    echo 'tag is $TAG'
    if (curl --silent -f -lSL https://hub.docker.com/v2/repositories/munique/openmu/tags/$TAG > /dev/null) then
      echo '##vso[task.setvariable variable=tagExists]true'
    else
      echo '##vso[task.setvariable variable=tagExists]false'
    fi
  env:
    TAG: $(projectVersion)
- task: Docker@2
  condition: eq(variables.tagExists, 'false')
  inputs:
   containerRegistry: 'munique docker hub'
   command: 'login'

- task: Docker@2
  displayName: "Build and Push All-In-One Image (openmu)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Startup/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push AdminPanel Image (openmu-admin)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/AdminPanel.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-admin'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push ChatServer Image"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/ChatServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-chat'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push ConnectServer Image (openmu-connect)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/ConnectServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-connect'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push FriendServer Image (openmu-friend)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/FriendServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-friend'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push GameServer Image (openmu-game)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/GameServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-game'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push GuildServer Image (openmu-guild)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/GuildServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-guild'
    tags: |
      $(projectVersion)
      latest
- task: Docker@2
  displayName: "Build and Push LoginServer Image (openmu-login)"
  condition: eq(variables.tagExists, 'false')
  inputs:
    containerRegistry: 'munique docker hub'
    command: 'buildAndPush'
    Dockerfile: 'src/Dapr/LoginServer.Host/Dockerfile'
    buildContext: 'src'
    repository: 'munique/openmu-login'
    tags: |
      $(projectVersion)
      latest
