//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;


    /// <summary>Provides strongly typed configuration name resources.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemDropDescriptions {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemDropDescriptions() {
        }

        /// <summary>Gets ResourceManager from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.ItemDropDescriptions", typeof(ItemDropDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Gets Culture from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Gets BoxOfLuckMoney from the configuration name resources.</summary>
        public static string BoxOfLuckMoney {
            get {
                return ResourceManager.GetString("BoxOfLuckMoney", resourceCulture);
            }
        }

        /// <summary>Gets RingOfWarrior80Money from the configuration name resources.</summary>
        public static string RingOfWarrior80Money {
            get {
                return ResourceManager.GetString("RingOfWarrior80Money", resourceCulture);
            }
        }

        /// <summary>Gets RingOfWarrior80 from the configuration name resources.</summary>
        public static string RingOfWarrior80 {
            get {
                return ResourceManager.GetString("RingOfWarrior80", resourceCulture);
            }
        }

        /// <summary>Gets RingOfWarrior40Money from the configuration name resources.</summary>
        public static string RingOfWarrior40Money {
            get {
                return ResourceManager.GetString("RingOfWarrior40Money", resourceCulture);
            }
        }

        /// <summary>Gets RingOfWarrior40 from the configuration name resources.</summary>
        public static string RingOfWarrior40 {
            get {
                return ResourceManager.GetString("RingOfWarrior40", resourceCulture);
            }
        }

        /// <summary>Gets HeartOfDarkLordMoney from the configuration name resources.</summary>
        public static string HeartOfDarkLordMoney {
            get {
                return ResourceManager.GetString("HeartOfDarkLordMoney", resourceCulture);
            }
        }

        /// <summary>Gets HeartOfDarkLord from the configuration name resources.</summary>
        public static string HeartOfDarkLord {
            get {
                return ResourceManager.GetString("HeartOfDarkLord", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus5Money from the configuration name resources.</summary>
        public static string BoxOfKundunPlus5Money {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus5Money", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus5 from the configuration name resources.</summary>
        public static string BoxOfKundunPlus5 {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus5", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus4Money from the configuration name resources.</summary>
        public static string BoxOfKundunPlus4Money {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus4Money", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus4 from the configuration name resources.</summary>
        public static string BoxOfKundunPlus4 {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus4", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus3Money from the configuration name resources.</summary>
        public static string BoxOfKundunPlus3Money {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus3Money", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus3 from the configuration name resources.</summary>
        public static string BoxOfKundunPlus3 {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus3", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus2Money from the configuration name resources.</summary>
        public static string BoxOfKundunPlus2Money {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus2Money", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus2 from the configuration name resources.</summary>
        public static string BoxOfKundunPlus2 {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus2", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus1Money from the configuration name resources.</summary>
        public static string BoxOfKundunPlus1Money {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus1Money", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfKundunPlus1 from the configuration name resources.</summary>
        public static string BoxOfKundunPlus1 {
            get {
                return ResourceManager.GetString("BoxOfKundunPlus1", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfHeavenMoney from the configuration name resources.</summary>
        public static string BoxOfHeavenMoney {
            get {
                return ResourceManager.GetString("BoxOfHeavenMoney", resourceCulture);
            }
        }

        /// <summary>Gets BoxOfHeaven from the configuration name resources.</summary>
        public static string BoxOfHeaven {
            get {
                return ResourceManager.GetString("BoxOfHeaven", resourceCulture);
            }
        }

        /// <summary>Gets GoldMedalMoney from the configuration name resources.</summary>
        public static string GoldMedalMoney {
            get {
                return ResourceManager.GetString("GoldMedalMoney", resourceCulture);
            }
        }

        /// <summary>Gets GoldMedal from the configuration name resources.</summary>
        public static string GoldMedal {
            get {
                return ResourceManager.GetString("GoldMedal", resourceCulture);
            }
        }

        /// <summary>Gets SilverMedalMoney from the configuration name resources.</summary>
        public static string SilverMedalMoney {
            get {
                return ResourceManager.GetString("SilverMedalMoney", resourceCulture);
            }
        }

        /// <summary>Gets SilverMedal from the configuration name resources.</summary>
        public static string SilverMedal {
            get {
                return ResourceManager.GetString("SilverMedal", resourceCulture);
            }
        }

        /// <summary>Gets HeartOfLoveItemsPlus7ToPlus9Money from the configuration name resources.</summary>
        public static string HeartOfLoveItemsPlus7ToPlus9Money {
            get {
                return ResourceManager.GetString("HeartOfLoveItemsPlus7ToPlus9Money", resourceCulture);
            }
        }

        /// <summary>Gets HeartOfLoveItemsPlus7ToPlus9 from the configuration name resources.</summary>
        public static string HeartOfLoveItemsPlus7ToPlus9 {
            get {
                return ResourceManager.GetString("HeartOfLoveItemsPlus7ToPlus9", resourceCulture);
            }
        }

        /// <summary>Gets HeartOfLoveJewelsEtc from the configuration name resources.</summary>
        public static string HeartOfLoveJewelsEtc {
            get {
                return ResourceManager.GetString("HeartOfLoveJewelsEtc", resourceCulture);
            }
        }

        /// <summary>Gets FirecrackerItemsPlus7ToPlus9Money from the configuration name resources.</summary>
        public static string FirecrackerItemsPlus7ToPlus9Money {
            get {
                return ResourceManager.GetString("FirecrackerItemsPlus7ToPlus9Money", resourceCulture);
            }
        }

        /// <summary>Gets FirecrackerItemsPlus7ToPlus9 from the configuration name resources.</summary>
        public static string FirecrackerItemsPlus7ToPlus9 {
            get {
                return ResourceManager.GetString("FirecrackerItemsPlus7ToPlus9", resourceCulture);
            }
        }

        /// <summary>Gets FirecrackerJewelsEtc from the configuration name resources.</summary>
        public static string FirecrackerJewelsEtc {
            get {
                return ResourceManager.GetString("FirecrackerJewelsEtc", resourceCulture);
            }
        }

        /// <summary>Gets StarOfTheSacredBirth from the configuration name resources.</summary>
        public static string StarOfTheSacredBirth {
            get {
                return ResourceManager.GetString("StarOfTheSacredBirth", resourceCulture);
            }
        }

        /// <summary>Gets FirecrackerDropEffect from the configuration name resources.</summary>
        public static string FirecrackerDropEffect {
            get {
                return ResourceManager.GetString("FirecrackerDropEffect", resourceCulture);
            }
        }

        /// <summary>Gets ChristmasFirecrackerDropEffect from the configuration name resources.</summary>
        public static string ChristmasFirecrackerDropEffect {
            get {
                return ResourceManager.GetString("ChristmasFirecrackerDropEffect", resourceCulture);
            }
        }

        /// <summary>Gets ChristmasStarDropEffect from the configuration name resources.</summary>
        public static string ChristmasStarDropEffect {
            get {
                return ResourceManager.GetString("ChristmasStarDropEffect", resourceCulture);
            }
        }

        /// <summary>Gets BlueRibbonBoxMoney from the configuration name resources.</summary>
        public static string BlueRibbonBoxMoney {
            get {
                return ResourceManager.GetString("BlueRibbonBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets BlueRibbonBoxExcellentItems from the configuration name resources.</summary>
        public static string BlueRibbonBoxExcellentItems {
            get {
                return ResourceManager.GetString("BlueRibbonBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets BlueRibbonBoxNormalItems from the configuration name resources.</summary>
        public static string BlueRibbonBoxNormalItems {
            get {
                return ResourceManager.GetString("BlueRibbonBoxNormalItems", resourceCulture);
            }
        }

        /// <summary>Gets GreenRibbonBoxMoney from the configuration name resources.</summary>
        public static string GreenRibbonBoxMoney {
            get {
                return ResourceManager.GetString("GreenRibbonBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets GreenRibbonBoxExcellentItems from the configuration name resources.</summary>
        public static string GreenRibbonBoxExcellentItems {
            get {
                return ResourceManager.GetString("GreenRibbonBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets GreenRibbonBoxNormalItems from the configuration name resources.</summary>
        public static string GreenRibbonBoxNormalItems {
            get {
                return ResourceManager.GetString("GreenRibbonBoxNormalItems", resourceCulture);
            }
        }

        /// <summary>Gets RedRibbonBoxMoney from the configuration name resources.</summary>
        public static string RedRibbonBoxMoney {
            get {
                return ResourceManager.GetString("RedRibbonBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets DeepBlueCandyBoxMoney from the configuration name resources.</summary>
        public static string DeepBlueCandyBoxMoney {
            get {
                return ResourceManager.GetString("DeepBlueCandyBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets BlueChocolateBoxExcellentItems from the configuration name resources.</summary>
        public static string BlueChocolateBoxExcellentItems {
            get {
                return ResourceManager.GetString("BlueChocolateBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets BlueChocolateBoxMoney from the configuration name resources.</summary>
        public static string BlueChocolateBoxMoney {
            get {
                return ResourceManager.GetString("BlueChocolateBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets VermilionCandyBoxMoney from the configuration name resources.</summary>
        public static string VermilionCandyBoxMoney {
            get {
                return ResourceManager.GetString("VermilionCandyBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets VermilionCandyBoxExcellentItems from the configuration name resources.</summary>
        public static string VermilionCandyBoxExcellentItems {
            get {
                return ResourceManager.GetString("VermilionCandyBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets VermilionCandyBoxNormalItems from the configuration name resources.</summary>
        public static string VermilionCandyBoxNormalItems {
            get {
                return ResourceManager.GetString("VermilionCandyBoxNormalItems", resourceCulture);
            }
        }

        /// <summary>Gets RedChocolateBoxMoney from the configuration name resources.</summary>
        public static string RedChocolateBoxMoney {
            get {
                return ResourceManager.GetString("RedChocolateBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets RedChocolateBoxExcellentItems from the configuration name resources.</summary>
        public static string RedChocolateBoxExcellentItems {
            get {
                return ResourceManager.GetString("RedChocolateBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets RedChocolateBoxNormalItems from the configuration name resources.</summary>
        public static string RedChocolateBoxNormalItems {
            get {
                return ResourceManager.GetString("RedChocolateBoxNormalItems", resourceCulture);
            }
        }

        /// <summary>Gets LightPurpleCandyBoxMoney from the configuration name resources.</summary>
        public static string LightPurpleCandyBoxMoney {
            get {
                return ResourceManager.GetString("LightPurpleCandyBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets LightPurpleCandyBoxExcellentItems from the configuration name resources.</summary>
        public static string LightPurpleCandyBoxExcellentItems {
            get {
                return ResourceManager.GetString("LightPurpleCandyBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets LightPurpleCandyBoxNormalItems from the configuration name resources.</summary>
        public static string LightPurpleCandyBoxNormalItems {
            get {
                return ResourceManager.GetString("LightPurpleCandyBoxNormalItems", resourceCulture);
            }
        }

        /// <summary>Gets PinkChocolateBoxMoney from the configuration name resources.</summary>
        public static string PinkChocolateBoxMoney {
            get {
                return ResourceManager.GetString("PinkChocolateBoxMoney", resourceCulture);
            }
        }

        /// <summary>Gets PinkChocolateBoxExcellentItems from the configuration name resources.</summary>
        public static string PinkChocolateBoxExcellentItems {
            get {
                return ResourceManager.GetString("PinkChocolateBoxExcellentItems", resourceCulture);
            }
        }

        /// <summary>Gets PinkChocolateBoxNormalItems from the configuration name resources.</summary>
        public static string PinkChocolateBoxNormalItems {
            get {
                return ResourceManager.GetString("PinkChocolateBoxNormalItems", resourceCulture);
            }
        }
    }
}
