//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;


    /// <summary>Provides strongly typed configuration name resources.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemSetNames {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemSetNames() {
        }

        /// <summary>Gets ResourceManager from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.ItemSetNames", typeof(ItemSetNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Gets Culture from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Gets Agnis from the configuration name resources.</summary>
        public static string Agnis {
            get {
                return ResourceManager.GetString("Agnis", resourceCulture);
            }
        }

        /// <summary>Gets Anonymous from the configuration name resources.</summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }

        /// <summary>Gets Anubis from the configuration name resources.</summary>
        public static string Anubis {
            get {
                return ResourceManager.GetString("Anubis", resourceCulture);
            }
        }

        /// <summary>Gets Apollo from the configuration name resources.</summary>
        public static string Apollo {
            get {
                return ResourceManager.GetString("Apollo", resourceCulture);
            }
        }

        /// <summary>Gets Argo from the configuration name resources.</summary>
        public static string Argo {
            get {
                return ResourceManager.GetString("Argo", resourceCulture);
            }
        }

        /// <summary>Gets Aruan from the configuration name resources.</summary>
        public static string Aruan {
            get {
                return ResourceManager.GetString("Aruan", resourceCulture);
            }
        }

        /// <summary>Gets Barnake from the configuration name resources.</summary>
        public static string Barnake {
            get {
                return ResourceManager.GetString("Barnake", resourceCulture);
            }
        }

        /// <summary>Gets Berserker from the configuration name resources.</summary>
        public static string Berserker {
            get {
                return ResourceManager.GetString("Berserker", resourceCulture);
            }
        }

        /// <summary>Gets Broy from the configuration name resources.</summary>
        public static string Broy {
            get {
                return ResourceManager.GetString("Broy", resourceCulture);
            }
        }

        /// <summary>Gets Ceto from the configuration name resources.</summary>
        public static string Ceto {
            get {
                return ResourceManager.GetString("Ceto", resourceCulture);
            }
        }

        /// <summary>Gets Chrono from the configuration name resources.</summary>
        public static string Chrono {
            get {
                return ResourceManager.GetString("Chrono", resourceCulture);
            }
        }

        /// <summary>Gets Cloud from the configuration name resources.</summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }

        /// <summary>Gets Drake from the configuration name resources.</summary>
        public static string Drake {
            get {
                return ResourceManager.GetString("Drake", resourceCulture);
            }
        }

        /// <summary>Gets Elvian from the configuration name resources.</summary>
        public static string Elvian {
            get {
                return ResourceManager.GetString("Elvian", resourceCulture);
            }
        }

        /// <summary>Gets Enis from the configuration name resources.</summary>
        public static string Enis {
            get {
                return ResourceManager.GetString("Enis", resourceCulture);
            }
        }

        /// <summary>Gets Eplete from the configuration name resources.</summary>
        public static string Eplete {
            get {
                return ResourceManager.GetString("Eplete", resourceCulture);
            }
        }

        /// <summary>Gets Evis from the configuration name resources.</summary>
        public static string Evis {
            get {
                return ResourceManager.GetString("Evis", resourceCulture);
            }
        }

        /// <summary>Gets Fase from the configuration name resources.</summary>
        public static string Fase {
            get {
                return ResourceManager.GetString("Fase", resourceCulture);
            }
        }

        /// <summary>Gets Gaia from the configuration name resources.</summary>
        public static string Gaia {
            get {
                return ResourceManager.GetString("Gaia", resourceCulture);
            }
        }

        /// <summary>Gets Gaion from the configuration name resources.</summary>
        public static string Gaion {
            get {
                return ResourceManager.GetString("Gaion", resourceCulture);
            }
        }

        /// <summary>Gets Garuda from the configuration name resources.</summary>
        public static string Garuda {
            get {
                return ResourceManager.GetString("Garuda", resourceCulture);
            }
        }

        /// <summary>Gets Gywen from the configuration name resources.</summary>
        public static string Gywen {
            get {
                return ResourceManager.GetString("Gywen", resourceCulture);
            }
        }

        /// <summary>Gets Heras from the configuration name resources.</summary>
        public static string Heras {
            get {
                return ResourceManager.GetString("Heras", resourceCulture);
            }
        }

        /// <summary>Gets Hyon from the configuration name resources.</summary>
        public static string Hyon {
            get {
                return ResourceManager.GetString("Hyon", resourceCulture);
            }
        }

        /// <summary>Gets Hyperion from the configuration name resources.</summary>
        public static string Hyperion {
            get {
                return ResourceManager.GetString("Hyperion", resourceCulture);
            }
        }

        /// <summary>Gets Kantata from the configuration name resources.</summary>
        public static string Kantata {
            get {
                return ResourceManager.GetString("Kantata", resourceCulture);
            }
        }

        /// <summary>Gets Karis from the configuration name resources.</summary>
        public static string Karis {
            get {
                return ResourceManager.GetString("Karis", resourceCulture);
            }
        }

        /// <summary>Gets Minet from the configuration name resources.</summary>
        public static string Minet {
            get {
                return ResourceManager.GetString("Minet", resourceCulture);
            }
        }

        /// <summary>Gets Mist from the configuration name resources.</summary>
        public static string Mist {
            get {
                return ResourceManager.GetString("Mist", resourceCulture);
            }
        }

        /// <summary>Gets Muren from the configuration name resources.</summary>
        public static string Muren {
            get {
                return ResourceManager.GetString("Muren", resourceCulture);
            }
        }

        /// <summary>Gets Odin from the configuration name resources.</summary>
        public static string Odin {
            get {
                return ResourceManager.GetString("Odin", resourceCulture);
            }
        }

        /// <summary>Gets Rave from the configuration name resources.</summary>
        public static string Rave {
            get {
                return ResourceManager.GetString("Rave", resourceCulture);
            }
        }

        /// <summary>Gets Semeden from the configuration name resources.</summary>
        public static string Semeden {
            get {
                return ResourceManager.GetString("Semeden", resourceCulture);
            }
        }

        /// <summary>Gets Sylion from the configuration name resources.</summary>
        public static string Sylion {
            get {
                return ResourceManager.GetString("Sylion", resourceCulture);
            }
        }

        /// <summary>Gets Vicious from the configuration name resources.</summary>
        public static string Vicious {
            get {
                return ResourceManager.GetString("Vicious", resourceCulture);
            }
        }

        /// <summary>Gets Warrior from the configuration name resources.</summary>
        public static string Warrior {
            get {
                return ResourceManager.GetString("Warrior", resourceCulture);
            }
        }
    }
}
