//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;


    /// <summary>Provides strongly typed configuration name resources.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemOptionNames {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemOptionNames() {
        }

        /// <summary>Gets ResourceManager from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.ItemOptionNames", typeof(ItemOptionNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Gets Culture from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Gets Level2ndWingOptions from the configuration name resources.</summary>
        public static string Level2ndWingOptions {
            get {
                return ResourceManager.GetString("Level2ndWingOptions", resourceCulture);
            }
        }

        /// <summary>Gets Level3rdWingOptions from the configuration name resources.</summary>
        public static string Level3rdWingOptions {
            get {
                return ResourceManager.GetString("Level3rdWingOptions", resourceCulture);
            }
        }

        /// <summary>Gets AgnisAncientSet from the configuration name resources.</summary>
        public static string AgnisAncientSet {
            get {
                return ResourceManager.GetString("AgnisAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets AncientBonusOfTotalAgility from the configuration name resources.</summary>
        public static string AncientBonusOfTotalAgility {
            get {
                return ResourceManager.GetString("AncientBonusOfTotalAgility", resourceCulture);
            }
        }

        /// <summary>Gets AncientBonusOfTotalEnergy from the configuration name resources.</summary>
        public static string AncientBonusOfTotalEnergy {
            get {
                return ResourceManager.GetString("AncientBonusOfTotalEnergy", resourceCulture);
            }
        }

        /// <summary>Gets AncientBonusOfTotalStrength from the configuration name resources.</summary>
        public static string AncientBonusOfTotalStrength {
            get {
                return ResourceManager.GetString("AncientBonusOfTotalStrength", resourceCulture);
            }
        }

        /// <summary>Gets AncientBonusOfTotalVitality from the configuration name resources.</summary>
        public static string AncientBonusOfTotalVitality {
            get {
                return ResourceManager.GetString("AncientBonusOfTotalVitality", resourceCulture);
            }
        }

        /// <summary>Gets AnonymousAncientSet from the configuration name resources.</summary>
        public static string AnonymousAncientSet {
            get {
                return ResourceManager.GetString("AnonymousAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets AnubisAncientSet from the configuration name resources.</summary>
        public static string AnubisAncientSet {
            get {
                return ResourceManager.GetString("AnubisAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets ApolloAncientSet from the configuration name resources.</summary>
        public static string ApolloAncientSet {
            get {
                return ResourceManager.GetString("ApolloAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets ArgoAncientSet from the configuration name resources.</summary>
        public static string ArgoAncientSet {
            get {
                return ResourceManager.GetString("ArgoAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets AruanAncientSet from the configuration name resources.</summary>
        public static string AruanAncientSet {
            get {
                return ResourceManager.GetString("AruanAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets BarnakeAncientSet from the configuration name resources.</summary>
        public static string BarnakeAncientSet {
            get {
                return ResourceManager.GetString("BarnakeAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets BaseDamageBonusPhysicalAndWizardryMinAndMaxOption from the configuration name resources.</summary>
        public static string BaseDamageBonusPhysicalAndWizardryMinAndMaxOption {
            get {
                return ResourceManager.GetString("BaseDamageBonusPhysicalAndWizardryMinAndMaxOption", resourceCulture);
            }
        }

        /// <summary>Gets BaseDefenseOption from the configuration name resources.</summary>
        public static string BaseDefenseOption {
            get {
                return ResourceManager.GetString("BaseDefenseOption", resourceCulture);
            }
        }

        /// <summary>Gets BerserkerAncientSet from the configuration name resources.</summary>
        public static string BerserkerAncientSet {
            get {
                return ResourceManager.GetString("BerserkerAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets BroyAncientSet from the configuration name resources.</summary>
        public static string BroyAncientSet {
            get {
                return ResourceManager.GetString("BroyAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets CapeOfEmperorOptions from the configuration name resources.</summary>
        public static string CapeOfEmperorOptions {
            get {
                return ResourceManager.GetString("CapeOfEmperorOptions", resourceCulture);
            }
        }

        /// <summary>Gets CapeOfFighterOptions from the configuration name resources.</summary>
        public static string CapeOfFighterOptions {
            get {
                return ResourceManager.GetString("CapeOfFighterOptions", resourceCulture);
            }
        }

        /// <summary>Gets CapeOfLordOptions from the configuration name resources.</summary>
        public static string CapeOfLordOptions {
            get {
                return ResourceManager.GetString("CapeOfLordOptions", resourceCulture);
            }
        }

        /// <summary>Gets CapeOfOverruleOptions from the configuration name resources.</summary>
        public static string CapeOfOverruleOptions {
            get {
                return ResourceManager.GetString("CapeOfOverruleOptions", resourceCulture);
            }
        }

        /// <summary>Gets CetoAncientSet from the configuration name resources.</summary>
        public static string CetoAncientSet {
            get {
                return ResourceManager.GetString("CetoAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets ChronoAncientSet from the configuration name resources.</summary>
        public static string ChronoAncientSet {
            get {
                return ResourceManager.GetString("ChronoAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets CloudAncientSet from the configuration name resources.</summary>
        public static string CloudAncientSet {
            get {
                return ResourceManager.GetString("CloudAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel10 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel10 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel10", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel11 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel11 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel11", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel12 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel12 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel12", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel13 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel13 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel13", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel14 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel14 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel14", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusLevel15 from the configuration name resources.</summary>
        public static string CompleteSetBonusLevel15 {
            get {
                return ResourceManager.GetString("CompleteSetBonusLevel15", resourceCulture);
            }
        }

        /// <summary>Gets CompleteSetBonusAnyLevel from the configuration name resources.</summary>
        public static string CompleteSetBonusAnyLevel {
            get {
                return ResourceManager.GetString("CompleteSetBonusAnyLevel", resourceCulture);
            }
        }

        /// <summary>Gets CurseBaseDamageMinAndMaxOption from the configuration name resources.</summary>
        public static string CurseBaseDamageMinAndMaxOption {
            get {
                return ResourceManager.GetString("CurseBaseDamageMinAndMaxOption", resourceCulture);
            }
        }

        /// <summary>Gets DarkHorseOptions from the configuration name resources.</summary>
        public static string DarkHorseOptions {
            get {
                return ResourceManager.GetString("DarkHorseOptions", resourceCulture);
            }
        }

        /// <summary>Gets DefenseRatePvMOption from the configuration name resources.</summary>
        public static string DefenseRatePvMOption {
            get {
                return ResourceManager.GetString("DefenseRatePvMOption", resourceCulture);
            }
        }

        /// <summary>Gets DinorantOptions from the configuration name resources.</summary>
        public static string DinorantOptions {
            get {
                return ResourceManager.GetString("DinorantOptions", resourceCulture);
            }
        }

        /// <summary>Gets DrakeAncientSet from the configuration name resources.</summary>
        public static string DrakeAncientSet {
            get {
                return ResourceManager.GetString("DrakeAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets EliteSkeletonTransformationRing from the configuration name resources.</summary>
        public static string EliteSkeletonTransformationRing {
            get {
                return ResourceManager.GetString("EliteSkeletonTransformationRing", resourceCulture);
            }
        }

        /// <summary>Gets ElvianAncientSet from the configuration name resources.</summary>
        public static string ElvianAncientSet {
            get {
                return ResourceManager.GetString("ElvianAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets EnisAncientSet from the configuration name resources.</summary>
        public static string EnisAncientSet {
            get {
                return ResourceManager.GetString("EnisAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets EpleteAncientSet from the configuration name resources.</summary>
        public static string EpleteAncientSet {
            get {
                return ResourceManager.GetString("EpleteAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets EvisAncientSet from the configuration name resources.</summary>
        public static string EvisAncientSet {
            get {
                return ResourceManager.GetString("EvisAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets ExcellentDefenseOptions from the configuration name resources.</summary>
        public static string ExcellentDefenseOptions {
            get {
                return ResourceManager.GetString("ExcellentDefenseOptions", resourceCulture);
            }
        }

        /// <summary>Gets ExcellentPhysicalAttackOptions from the configuration name resources.</summary>
        public static string ExcellentPhysicalAttackOptions {
            get {
                return ResourceManager.GetString("ExcellentPhysicalAttackOptions", resourceCulture);
            }
        }

        /// <summary>Gets ExcellentWizardryAttackOptions from the configuration name resources.</summary>
        public static string ExcellentWizardryAttackOptions {
            get {
                return ResourceManager.GetString("ExcellentWizardryAttackOptions", resourceCulture);
            }
        }

        /// <summary>Gets FaseAncientSet from the configuration name resources.</summary>
        public static string FaseAncientSet {
            get {
                return ResourceManager.GetString("FaseAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets FenrirOptions from the configuration name resources.</summary>
        public static string FenrirOptions {
            get {
                return ResourceManager.GetString("FenrirOptions", resourceCulture);
            }
        }

        /// <summary>Gets GaiaAncientSet from the configuration name resources.</summary>
        public static string GaiaAncientSet {
            get {
                return ResourceManager.GetString("GaiaAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets GaionAncientSet from the configuration name resources.</summary>
        public static string GaionAncientSet {
            get {
                return ResourceManager.GetString("GaionAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets GarudaAncientSet from the configuration name resources.</summary>
        public static string GarudaAncientSet {
            get {
                return ResourceManager.GetString("GarudaAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionArmor from the configuration name resources.</summary>
        public static string GuardianOptionArmor {
            get {
                return ResourceManager.GetString("GuardianOptionArmor", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionBoots from the configuration name resources.</summary>
        public static string GuardianOptionBoots {
            get {
                return ResourceManager.GetString("GuardianOptionBoots", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionGloves from the configuration name resources.</summary>
        public static string GuardianOptionGloves {
            get {
                return ResourceManager.GetString("GuardianOptionGloves", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionHelm from the configuration name resources.</summary>
        public static string GuardianOptionHelm {
            get {
                return ResourceManager.GetString("GuardianOptionHelm", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionPants from the configuration name resources.</summary>
        public static string GuardianOptionPants {
            get {
                return ResourceManager.GetString("GuardianOptionPants", resourceCulture);
            }
        }

        /// <summary>Gets GuardianOptionWeapon from the configuration name resources.</summary>
        public static string GuardianOptionWeapon {
            get {
                return ResourceManager.GetString("GuardianOptionWeapon", resourceCulture);
            }
        }

        /// <summary>Gets GywenAncientSet from the configuration name resources.</summary>
        public static string GywenAncientSet {
            get {
                return ResourceManager.GetString("GywenAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets HarmonyDefenseOptions from the configuration name resources.</summary>
        public static string HarmonyDefenseOptions {
            get {
                return ResourceManager.GetString("HarmonyDefenseOptions", resourceCulture);
            }
        }

        /// <summary>Gets HarmonyPhysicalAttackOptions from the configuration name resources.</summary>
        public static string HarmonyPhysicalAttackOptions {
            get {
                return ResourceManager.GetString("HarmonyPhysicalAttackOptions", resourceCulture);
            }
        }

        /// <summary>Gets HarmonyWizardryAttackOptions from the configuration name resources.</summary>
        public static string HarmonyWizardryAttackOptions {
            get {
                return ResourceManager.GetString("HarmonyWizardryAttackOptions", resourceCulture);
            }
        }

        /// <summary>Gets HealthRecoverForJewelery from the configuration name resources.</summary>
        public static string HealthRecoverForJewelery {
            get {
                return ResourceManager.GetString("HealthRecoverForJewelery", resourceCulture);
            }
        }

        /// <summary>Gets HerasAncientSet from the configuration name resources.</summary>
        public static string HerasAncientSet {
            get {
                return ResourceManager.GetString("HerasAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets HyonAncientSet from the configuration name resources.</summary>
        public static string HyonAncientSet {
            get {
                return ResourceManager.GetString("HyonAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets HyperionAncientSet from the configuration name resources.</summary>
        public static string HyperionAncientSet {
            get {
                return ResourceManager.GetString("HyperionAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets JeweleryOptionMaximumAbility from the configuration name resources.</summary>
        public static string JeweleryOptionMaximumAbility {
            get {
                return ResourceManager.GetString("JeweleryOptionMaximumAbility", resourceCulture);
            }
        }

        /// <summary>Gets JeweleryOptionMaximumMana from the configuration name resources.</summary>
        public static string JeweleryOptionMaximumMana {
            get {
                return ResourceManager.GetString("JeweleryOptionMaximumMana", resourceCulture);
            }
        }

        /// <summary>Gets KantataAncientSet from the configuration name resources.</summary>
        public static string KantataAncientSet {
            get {
                return ResourceManager.GetString("KantataAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets KarisAncientSet from the configuration name resources.</summary>
        public static string KarisAncientSet {
            get {
                return ResourceManager.GetString("KarisAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets Luck from the configuration name resources.</summary>
        public static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }

        /// <summary>Gets MinetAncientSet from the configuration name resources.</summary>
        public static string MinetAncientSet {
            get {
                return ResourceManager.GetString("MinetAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets MistAncientSet from the configuration name resources.</summary>
        public static string MistAncientSet {
            get {
                return ResourceManager.GetString("MistAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets MurenAncientSet from the configuration name resources.</summary>
        public static string MurenAncientSet {
            get {
                return ResourceManager.GetString("MurenAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets OdinAncientSet from the configuration name resources.</summary>
        public static string OdinAncientSet {
            get {
                return ResourceManager.GetString("OdinAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets PhysicalBaseDamageMinAndMaxOption from the configuration name resources.</summary>
        public static string PhysicalBaseDamageMinAndMaxOption {
            get {
                return ResourceManager.GetString("PhysicalBaseDamageMinAndMaxOption", resourceCulture);
            }
        }

        /// <summary>Gets RaveAncientSet from the configuration name resources.</summary>
        public static string RaveAncientSet {
            get {
                return ResourceManager.GetString("RaveAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets SemedenAncientSet from the configuration name resources.</summary>
        public static string SemedenAncientSet {
            get {
                return ResourceManager.GetString("SemedenAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets SkeletonTransformationRing from the configuration name resources.</summary>
        public static string SkeletonTransformationRing {
            get {
                return ResourceManager.GetString("SkeletonTransformationRing", resourceCulture);
            }
        }

        /// <summary>Gets SocketBonusOptionsArmors from the configuration name resources.</summary>
        public static string SocketBonusOptionsArmors {
            get {
                return ResourceManager.GetString("SocketBonusOptionsArmors", resourceCulture);
            }
        }

        /// <summary>Gets SocketBonusOptionsPhysical from the configuration name resources.</summary>
        public static string SocketBonusOptionsPhysical {
            get {
                return ResourceManager.GetString("SocketBonusOptionsPhysical", resourceCulture);
            }
        }

        /// <summary>Gets SocketBonusOptionsWizardry from the configuration name resources.</summary>
        public static string SocketBonusOptionsWizardry {
            get {
                return ResourceManager.GetString("SocketBonusOptionsWizardry", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsEarth from the configuration name resources.</summary>
        public static string SocketOptionsEarth {
            get {
                return ResourceManager.GetString("SocketOptionsEarth", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsFire from the configuration name resources.</summary>
        public static string SocketOptionsFire {
            get {
                return ResourceManager.GetString("SocketOptionsFire", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsIce from the configuration name resources.</summary>
        public static string SocketOptionsIce {
            get {
                return ResourceManager.GetString("SocketOptionsIce", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsLightning from the configuration name resources.</summary>
        public static string SocketOptionsLightning {
            get {
                return ResourceManager.GetString("SocketOptionsLightning", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsWater from the configuration name resources.</summary>
        public static string SocketOptionsWater {
            get {
                return ResourceManager.GetString("SocketOptionsWater", resourceCulture);
            }
        }

        /// <summary>Gets SocketOptionsWind from the configuration name resources.</summary>
        public static string SocketOptionsWind {
            get {
                return ResourceManager.GetString("SocketOptionsWind", resourceCulture);
            }
        }

        /// <summary>Gets SylionAncientSet from the configuration name resources.</summary>
        public static string SylionAncientSet {
            get {
                return ResourceManager.GetString("SylionAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets ViciousAncientSet from the configuration name resources.</summary>
        public static string ViciousAncientSet {
            get {
                return ResourceManager.GetString("ViciousAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets WarriorAncientSet from the configuration name resources.</summary>
        public static string WarriorAncientSet {
            get {
                return ResourceManager.GetString("WarriorAncientSet", resourceCulture);
            }
        }

        /// <summary>Gets WingOfDimensionOptions from the configuration name resources.</summary>
        public static string WingOfDimensionOptions {
            get {
                return ResourceManager.GetString("WingOfDimensionOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingOfEternalOptions from the configuration name resources.</summary>
        public static string WingOfEternalOptions {
            get {
                return ResourceManager.GetString("WingOfEternalOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingOfIllusionOptions from the configuration name resources.</summary>
        public static string WingOfIllusionOptions {
            get {
                return ResourceManager.GetString("WingOfIllusionOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingOfRuinOptions from the configuration name resources.</summary>
        public static string WingOfRuinOptions {
            get {
                return ResourceManager.GetString("WingOfRuinOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingOfStormOptions from the configuration name resources.</summary>
        public static string WingOfStormOptions {
            get {
                return ResourceManager.GetString("WingOfStormOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfCurseOptions from the configuration name resources.</summary>
        public static string WingsOfCurseOptions {
            get {
                return ResourceManager.GetString("WingsOfCurseOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfDarknessOptions from the configuration name resources.</summary>
        public static string WingsOfDarknessOptions {
            get {
                return ResourceManager.GetString("WingsOfDarknessOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfDespairOptions from the configuration name resources.</summary>
        public static string WingsOfDespairOptions {
            get {
                return ResourceManager.GetString("WingsOfDespairOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfDragonOptions from the configuration name resources.</summary>
        public static string WingsOfDragonOptions {
            get {
                return ResourceManager.GetString("WingsOfDragonOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfElfOptions from the configuration name resources.</summary>
        public static string WingsOfElfOptions {
            get {
                return ResourceManager.GetString("WingsOfElfOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfHeavenOptions from the configuration name resources.</summary>
        public static string WingsOfHeavenOptions {
            get {
                return ResourceManager.GetString("WingsOfHeavenOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfSatanOptions from the configuration name resources.</summary>
        public static string WingsOfSatanOptions {
            get {
                return ResourceManager.GetString("WingsOfSatanOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfSoulOptions from the configuration name resources.</summary>
        public static string WingsOfSoulOptions {
            get {
                return ResourceManager.GetString("WingsOfSoulOptions", resourceCulture);
            }
        }

        /// <summary>Gets WingsOfSpiritsOptions from the configuration name resources.</summary>
        public static string WingsOfSpiritsOptions {
            get {
                return ResourceManager.GetString("WingsOfSpiritsOptions", resourceCulture);
            }
        }

        /// <summary>Gets WizardryBaseDamageMinAndMaxOption from the configuration name resources.</summary>
        public static string WizardryBaseDamageMinAndMaxOption {
            get {
                return ResourceManager.GetString("WizardryBaseDamageMinAndMaxOption", resourceCulture);
            }
        }
    }
}
