//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.MapNames", typeof(MapNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aida.
        /// </summary>
        public static string Aida {
            get {
                return ResourceManager.GetString("Aida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlans.
        /// </summary>
        public static string Atlans {
            get {
                return ResourceManager.GetString("Atlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balgass Refuge.
        /// </summary>
        public static string BalgassRefuge {
            get {
                return ResourceManager.GetString("BalgassRefuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks of Balgass.
        /// </summary>
        public static string BarracksOfBalgass {
            get {
                return ResourceManager.GetString("BarracksOfBalgass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 1.
        /// </summary>
        public static string BloodCastle1 {
            get {
                return ResourceManager.GetString("BloodCastle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 2.
        /// </summary>
        public static string BloodCastle2 {
            get {
                return ResourceManager.GetString("BloodCastle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 3.
        /// </summary>
        public static string BloodCastle3 {
            get {
                return ResourceManager.GetString("BloodCastle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 4.
        /// </summary>
        public static string BloodCastle4 {
            get {
                return ResourceManager.GetString("BloodCastle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 5.
        /// </summary>
        public static string BloodCastle5 {
            get {
                return ResourceManager.GetString("BloodCastle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 6.
        /// </summary>
        public static string BloodCastle6 {
            get {
                return ResourceManager.GetString("BloodCastle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 7.
        /// </summary>
        public static string BloodCastle7 {
            get {
                return ResourceManager.GetString("BloodCastle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Castle 8.
        /// </summary>
        public static string BloodCastle8 {
            get {
                return ResourceManager.GetString("BloodCastle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 1.
        /// </summary>
        public static string ChaosCastle1 {
            get {
                return ResourceManager.GetString("ChaosCastle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 2.
        /// </summary>
        public static string ChaosCastle2 {
            get {
                return ResourceManager.GetString("ChaosCastle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 3.
        /// </summary>
        public static string ChaosCastle3 {
            get {
                return ResourceManager.GetString("ChaosCastle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 4.
        /// </summary>
        public static string ChaosCastle4 {
            get {
                return ResourceManager.GetString("ChaosCastle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 5.
        /// </summary>
        public static string ChaosCastle5 {
            get {
                return ResourceManager.GetString("ChaosCastle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 6.
        /// </summary>
        public static string ChaosCastle6 {
            get {
                return ResourceManager.GetString("ChaosCastle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Castle 7.
        /// </summary>
        public static string ChaosCastle7 {
            get {
                return ResourceManager.GetString("ChaosCastle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crywolf Fortress.
        /// </summary>
        public static string CrywolfFortress {
            get {
                return ResourceManager.GetString("CrywolfFortress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devias.
        /// </summary>
        public static string Devias {
            get {
                return ResourceManager.GetString("Devias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 1.
        /// </summary>
        public static string DevilSquare1 {
            get {
                return ResourceManager.GetString("DevilSquare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 2.
        /// </summary>
        public static string DevilSquare2 {
            get {
                return ResourceManager.GetString("DevilSquare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 3.
        /// </summary>
        public static string DevilSquare3 {
            get {
                return ResourceManager.GetString("DevilSquare3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 4.
        /// </summary>
        public static string DevilSquare4 {
            get {
                return ResourceManager.GetString("DevilSquare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 5.
        /// </summary>
        public static string DevilSquare5 {
            get {
                return ResourceManager.GetString("DevilSquare5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 6.
        /// </summary>
        public static string DevilSquare6 {
            get {
                return ResourceManager.GetString("DevilSquare6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devil Square 7.
        /// </summary>
        public static string DevilSquare7 {
            get {
                return ResourceManager.GetString("DevilSquare7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelgaenger 1.
        /// </summary>
        public static string Doppelgaenger1 {
            get {
                return ResourceManager.GetString("Doppelgaenger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelgaenger 2.
        /// </summary>
        public static string Doppelgaenger2 {
            get {
                return ResourceManager.GetString("Doppelgaenger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelgaenger 3.
        /// </summary>
        public static string Doppelgaenger3 {
            get {
                return ResourceManager.GetString("Doppelgaenger3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelgaenger 4.
        /// </summary>
        public static string Doppelgaenger4 {
            get {
                return ResourceManager.GetString("Doppelgaenger4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel Arena.
        /// </summary>
        public static string DuelArena {
            get {
                return ResourceManager.GetString("DuelArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        public static string Dungeon {
            get {
                return ResourceManager.GetString("Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elvenland.
        /// </summary>
        public static string Elvenland {
            get {
                return ResourceManager.GetString("Elvenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortress of Imperial Guardian 1.
        /// </summary>
        public static string FortressOfImperialGuardian1 {
            get {
                return ResourceManager.GetString("FortressOfImperialGuardian1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortress of Imperial Guardian 2.
        /// </summary>
        public static string FortressOfImperialGuardian2 {
            get {
                return ResourceManager.GetString("FortressOfImperialGuardian2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortress of Imperial Guardian 3.
        /// </summary>
        public static string FortressOfImperialGuardian3 {
            get {
                return ResourceManager.GetString("FortressOfImperialGuardian3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortress of Imperial Guardian 4.
        /// </summary>
        public static string FortressOfImperialGuardian4 {
            get {
                return ResourceManager.GetString("FortressOfImperialGuardian4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icarus.
        /// </summary>
        public static string Icarus {
            get {
                return ResourceManager.GetString("Icarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 1.
        /// </summary>
        public static string IllusionTemple1 {
            get {
                return ResourceManager.GetString("IllusionTemple1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 2.
        /// </summary>
        public static string IllusionTemple2 {
            get {
                return ResourceManager.GetString("IllusionTemple2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 3.
        /// </summary>
        public static string IllusionTemple3 {
            get {
                return ResourceManager.GetString("IllusionTemple3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 4.
        /// </summary>
        public static string IllusionTemple4 {
            get {
                return ResourceManager.GetString("IllusionTemple4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 5.
        /// </summary>
        public static string IllusionTemple5 {
            get {
                return ResourceManager.GetString("IllusionTemple5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion Temple 6.
        /// </summary>
        public static string IllusionTemple6 {
            get {
                return ResourceManager.GetString("IllusionTemple6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 1.
        /// </summary>
        public static string Kalima1 {
            get {
                return ResourceManager.GetString("Kalima1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 2.
        /// </summary>
        public static string Kalima2 {
            get {
                return ResourceManager.GetString("Kalima2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 3.
        /// </summary>
        public static string Kalima3 {
            get {
                return ResourceManager.GetString("Kalima3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 4.
        /// </summary>
        public static string Kalima4 {
            get {
                return ResourceManager.GetString("Kalima4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 5.
        /// </summary>
        public static string Kalima5 {
            get {
                return ResourceManager.GetString("Kalima5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 6.
        /// </summary>
        public static string Kalima6 {
            get {
                return ResourceManager.GetString("Kalima6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalima 7.
        /// </summary>
        public static string Kalima7 {
            get {
                return ResourceManager.GetString("Kalima7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanturu Event.
        /// </summary>
        public static string KanturuEvent {
            get {
                return ResourceManager.GetString("KanturuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanturu_I.
        /// </summary>
        public static string KanturuI {
            get {
                return ResourceManager.GetString("KanturuI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanturu_III.
        /// </summary>
        public static string KanturuIII {
            get {
                return ResourceManager.GetString("KanturuIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karutan 1.
        /// </summary>
        public static string Karutan1 {
            get {
                return ResourceManager.GetString("Karutan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karutan 2.
        /// </summary>
        public static string Karutan2 {
            get {
                return ResourceManager.GetString("Karutan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaCleon.
        /// </summary>
        public static string LaCleon {
            get {
                return ResourceManager.GetString("LaCleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaCleon Boss.
        /// </summary>
        public static string LaCleonBoss {
            get {
                return ResourceManager.GetString("LaCleonBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land_of_Trials.
        /// </summary>
        public static string LandOfTrials {
            get {
                return ResourceManager.GetString("LandOfTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorencia.
        /// </summary>
        public static string Lorencia {
            get {
                return ResourceManager.GetString("Lorencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LorenMarket.
        /// </summary>
        public static string LorenMarket {
            get {
                return ResourceManager.GetString("LorenMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Tower.
        /// </summary>
        public static string LostTower {
            get {
                return ResourceManager.GetString("LostTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noria.
        /// </summary>
        public static string Noria {
            get {
                return ResourceManager.GetString("Noria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp Of Calmness.
        /// </summary>
        public static string SwampOfCalmness {
            get {
                return ResourceManager.GetString("SwampOfCalmness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkan.
        /// </summary>
        public static string Tarkan {
            get {
                return ResourceManager.GetString("Tarkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valley of Loren.
        /// </summary>
        public static string ValleyOfLoren {
            get {
                return ResourceManager.GetString("ValleyOfLoren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulcanus.
        /// </summary>
        public static string Vulcanus {
            get {
                return ResourceManager.GetString("Vulcanus", resourceCulture);
            }
        }
    }
}
