//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;


    /// <summary>Provides strongly typed configuration name resources.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterSkillRootNames {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterSkillRootNames() {
        }

        /// <summary>Gets ResourceManager from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.MasterSkillRootNames", typeof(MasterSkillRootNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Gets Culture from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Gets RightRoot from the configuration name resources.</summary>
        public static string RightRoot {
            get {
                return ResourceManager.GetString("RightRoot", resourceCulture);
            }
        }

        /// <summary>Gets MiddleRoot from the configuration name resources.</summary>
        public static string MiddleRoot {
            get {
                return ResourceManager.GetString("MiddleRoot", resourceCulture);
            }
        }

        /// <summary>Gets LeftCommonSkills from the configuration name resources.</summary>
        public static string LeftCommonSkills {
            get {
                return ResourceManager.GetString("LeftCommonSkills", resourceCulture);
            }
        }
    }
}
