//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Persistence.Initialization.Properties {
    using System;


    /// <summary>Provides strongly typed configuration name resources.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarpNames {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarpNames() {
        }

        /// <summary>Gets ResourceManager from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MUnique.OpenMU.Persistence.Initialization.Properties.WarpNames", typeof(WarpNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Gets Culture from the configuration name resources.</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Gets LostTower7 from the configuration name resources.</summary>
        public static string LostTower7 {
            get {
                return ResourceManager.GetString("LostTower7", resourceCulture);
            }
        }

        /// <summary>Gets LostTower6 from the configuration name resources.</summary>
        public static string LostTower6 {
            get {
                return ResourceManager.GetString("LostTower6", resourceCulture);
            }
        }

        /// <summary>Gets LostTower5 from the configuration name resources.</summary>
        public static string LostTower5 {
            get {
                return ResourceManager.GetString("LostTower5", resourceCulture);
            }
        }

        /// <summary>Gets LostTower4 from the configuration name resources.</summary>
        public static string LostTower4 {
            get {
                return ResourceManager.GetString("LostTower4", resourceCulture);
            }
        }

        /// <summary>Gets LostTower3 from the configuration name resources.</summary>
        public static string LostTower3 {
            get {
                return ResourceManager.GetString("LostTower3", resourceCulture);
            }
        }

        /// <summary>Gets LostTower2 from the configuration name resources.</summary>
        public static string LostTower2 {
            get {
                return ResourceManager.GetString("LostTower2", resourceCulture);
            }
        }

        /// <summary>Gets LostTower from the configuration name resources.</summary>
        public static string LostTower {
            get {
                return ResourceManager.GetString("LostTower", resourceCulture);
            }
        }

        /// <summary>Gets Dungeon3 from the configuration name resources.</summary>
        public static string Dungeon3 {
            get {
                return ResourceManager.GetString("Dungeon3", resourceCulture);
            }
        }

        /// <summary>Gets Dungeon2 from the configuration name resources.</summary>
        public static string Dungeon2 {
            get {
                return ResourceManager.GetString("Dungeon2", resourceCulture);
            }
        }

        /// <summary>Gets Dungeon from the configuration name resources.</summary>
        public static string Dungeon {
            get {
                return ResourceManager.GetString("Dungeon", resourceCulture);
            }
        }

        /// <summary>Gets Devias from the configuration name resources.</summary>
        public static string Devias {
            get {
                return ResourceManager.GetString("Devias", resourceCulture);
            }
        }

        /// <summary>Gets Noria from the configuration name resources.</summary>
        public static string Noria {
            get {
                return ResourceManager.GetString("Noria", resourceCulture);
            }
        }

        /// <summary>Gets Lorencia from the configuration name resources.</summary>
        public static string Lorencia {
            get {
                return ResourceManager.GetString("Lorencia", resourceCulture);
            }
        }

        /// <summary>Gets Arena from the configuration name resources.</summary>
        public static string Arena {
            get {
                return ResourceManager.GetString("Arena", resourceCulture);
            }
        }

        /// <summary>Gets LaCleon from the configuration name resources.</summary>
        public static string LaCleon {
            get {
                return ResourceManager.GetString("LaCleon", resourceCulture);
            }
        }

        /// <summary>Gets Karutan2 from the configuration name resources.</summary>
        public static string Karutan2 {
            get {
                return ResourceManager.GetString("Karutan2", resourceCulture);
            }
        }

        /// <summary>Gets Karutan1 from the configuration name resources.</summary>
        public static string Karutan1 {
            get {
                return ResourceManager.GetString("Karutan1", resourceCulture);
            }
        }

        /// <summary>Gets KanturuRuins3 from the configuration name resources.</summary>
        public static string KanturuRuins3 {
            get {
                return ResourceManager.GetString("KanturuRuins3", resourceCulture);
            }
        }

        /// <summary>Gets Elveland3 from the configuration name resources.</summary>
        public static string Elveland3 {
            get {
                return ResourceManager.GetString("Elveland3", resourceCulture);
            }
        }

        /// <summary>Gets LorenMarket from the configuration name resources.</summary>
        public static string LorenMarket {
            get {
                return ResourceManager.GetString("LorenMarket", resourceCulture);
            }
        }

        /// <summary>Gets Vulcanus from the configuration name resources.</summary>
        public static string Vulcanus {
            get {
                return ResourceManager.GetString("Vulcanus", resourceCulture);
            }
        }

        /// <summary>Gets Raklion from the configuration name resources.</summary>
        public static string Raklion {
            get {
                return ResourceManager.GetString("Raklion", resourceCulture);
            }
        }

        /// <summary>Gets PeaceSwamp from the configuration name resources.</summary>
        public static string PeaceSwamp {
            get {
                return ResourceManager.GetString("PeaceSwamp", resourceCulture);
            }
        }

        /// <summary>Gets Elveland2 from the configuration name resources.</summary>
        public static string Elveland2 {
            get {
                return ResourceManager.GetString("Elveland2", resourceCulture);
            }
        }

        /// <summary>Gets Elveland from the configuration name resources.</summary>
        public static string Elveland {
            get {
                return ResourceManager.GetString("Elveland", resourceCulture);
            }
        }

        /// <summary>Gets KanturuRelics from the configuration name resources.</summary>
        public static string KanturuRelics {
            get {
                return ResourceManager.GetString("KanturuRelics", resourceCulture);
            }
        }

        /// <summary>Gets KanturuRuins2 from the configuration name resources.</summary>
        public static string KanturuRuins2 {
            get {
                return ResourceManager.GetString("KanturuRuins2", resourceCulture);
            }
        }

        /// <summary>Gets KanturuRuins1 from the configuration name resources.</summary>
        public static string KanturuRuins1 {
            get {
                return ResourceManager.GetString("KanturuRuins1", resourceCulture);
            }
        }

        /// <summary>Gets Aida2 from the configuration name resources.</summary>
        public static string Aida2 {
            get {
                return ResourceManager.GetString("Aida2", resourceCulture);
            }
        }

        /// <summary>Gets Aida1 from the configuration name resources.</summary>
        public static string Aida1 {
            get {
                return ResourceManager.GetString("Aida1", resourceCulture);
            }
        }

        /// <summary>Gets Icarus from the configuration name resources.</summary>
        public static string Icarus {
            get {
                return ResourceManager.GetString("Icarus", resourceCulture);
            }
        }

        /// <summary>Gets Tarkan2 from the configuration name resources.</summary>
        public static string Tarkan2 {
            get {
                return ResourceManager.GetString("Tarkan2", resourceCulture);
            }
        }

        /// <summary>Gets Tarkan from the configuration name resources.</summary>
        public static string Tarkan {
            get {
                return ResourceManager.GetString("Tarkan", resourceCulture);
            }
        }

        /// <summary>Gets Atlans3 from the configuration name resources.</summary>
        public static string Atlans3 {
            get {
                return ResourceManager.GetString("Atlans3", resourceCulture);
            }
        }

        /// <summary>Gets Atlans2 from the configuration name resources.</summary>
        public static string Atlans2 {
            get {
                return ResourceManager.GetString("Atlans2", resourceCulture);
            }
        }

        /// <summary>Gets Atlans from the configuration name resources.</summary>
        public static string Atlans {
            get {
                return ResourceManager.GetString("Atlans", resourceCulture);
            }
        }

        /// <summary>Gets Devias4 from the configuration name resources.</summary>
        public static string Devias4 {
            get {
                return ResourceManager.GetString("Devias4", resourceCulture);
            }
        }

        /// <summary>Gets Devias3 from the configuration name resources.</summary>
        public static string Devias3 {
            get {
                return ResourceManager.GetString("Devias3", resourceCulture);
            }
        }

        /// <summary>Gets Devias2 from the configuration name resources.</summary>
        public static string Devias2 {
            get {
                return ResourceManager.GetString("Devias2", resourceCulture);
            }
        }
    }
}
