// <copyright file="Buff.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.EntityFramework.Model;

using System.ComponentModel.DataAnnotations.Schema;
using MUnique.OpenMU.Persistence;

/// <summary>
/// The Entity Framework Core implementation of <see cref="MUnique.OpenMU.DataModel.Configuration.Buff"/>.
/// </summary>
[Table(nameof(Buff), Schema = SchemaNames.Configuration)]
internal partial class Buff : MUnique.OpenMU.DataModel.Configuration.Buff, IIdentifiable
{
    
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets or sets the identifier of <see cref="MagicEffectDefinition"/>.
    /// </summary>
    public Guid? MagicEffectDefinitionId { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="MagicEffectDefinition" />.
    /// </summary>
    [ForeignKey(nameof(MagicEffectDefinitionId))]
    public MagicEffectDefinition RawMagicEffectDefinition
    {
        get => base.MagicEffectDefinition as MagicEffectDefinition;
        set => base.MagicEffectDefinition = value;
    }

    /// <inheritdoc/>
    [NotMapped]
    public override MUnique.OpenMU.DataModel.Configuration.MagicEffectDefinition MagicEffectDefinition
    {
        get => base.MagicEffectDefinition;set
        {
            base.MagicEffectDefinition = value;
            this.MagicEffectDefinitionId = this.RawMagicEffectDefinition?.Id;
        }
    }

    /// <inheritdoc />
    public override MUnique.OpenMU.DataModel.Configuration.Buff Clone(MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        var clone = new Buff();
        clone.AssignValuesOf(this, gameConfiguration);
        return clone;
    }
    
    /// <inheritdoc />
    public override void AssignValuesOf(MUnique.OpenMU.DataModel.Configuration.Buff other, MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        base.AssignValuesOf(other, gameConfiguration);
        this.Id = other.GetId();
    }

    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    
}
