// <copyright file="ChineseMonsterNames.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.Persistence.Initialization;

using System.Globalization;
using MUnique.OpenMU.DataModel.Configuration;

/// <summary>
/// Adds Simplified Chinese monster names while preserving customized translations.
/// </summary>
internal static class ChineseMonsterNames
{
    private static readonly CultureInfo ChineseCulture = CultureInfo.GetCultureInfo("zh-CN");
    private static readonly IReadOnlyDictionary<short, (string NeutralName, string ChineseName)> NamesByNumber =
        new Dictionary<short, (string NeutralName, string ChineseName)>
        {
            [0] = ("Bull Fighter", "牛怪"),
            [1] = ("Hound", "猎犬怪"),
            [2] = ("Budge Dragon", "幼龙"),
            [3] = ("Spider", "蜘蛛"),
            [4] = ("Elite Bull Fighter", "蛮牛怪"),
            [5] = ("Hell Hound", "地狱猎犬怪"),
            [6] = ("Lich", "黑巫师"),
            [7] = ("Giant", "巨人"),
            [8] = ("Poison Bull", "毒牛怪"),
            [9] = ("Thunder Lich", "死灵巫师"),
            [10] = ("Dark Knight", "暗黑骑士"),
            [11] = ("Ghost", "幽灵"),
            [12] = ("Larva", "毒虫"),
            [13] = ("Hell Spider", "地狱蜘蛛"),
            [14] = ("Skeleton Warrior", "骷髅兵"),
            [15] = ("Skeleton Archer", "骷髅弓箭手"),
            [16] = ("Elite Skeleton", "骷髅战士"),
            [17] = ("Cyclops", "独眼巨人"),
            [18] = ("Gorgon", "魔鬼戈登"),
            [19] = ("Yeti", "雪人"),
            [20] = ("Elite Yeti", "雪人王"),
            [21] = ("Assassin", "暗杀者"),
            [22] = ("Ice Monster", "寒冰魔"),
            [23] = ("Hommerd", "蓝魔怪"),
            [24] = ("Worm", "雪虫"),
            [25] = ("Ice Queen", "冰后"),
            [26] = ("Goblin", "小哥布林"),
            [27] = ("Chain Scorpion", "勾尾蝎"),
            [28] = ("Beetle Monster", "瓢虫怪"),
            [29] = ("Hunter", "偷猎者"),
            [30] = ("Forest Monster", "树妖"),
            [31] = ("Agon", "亚昆"),
            [32] = ("Stone Golem", "石巨人"),
            [33] = ("Elite Goblin", "大哥布林"),
            [34] = ("Cursed Wizard", "诅咒巫师"),
            [35] = ("Death Gorgon", "死神戈登"),
            [36] = ("Shadow", "鬼魅"),
            [37] = ("Devil", "恶魔"),
            [38] = ("Balrog", "魔王巴洛克"),
            [39] = ("Poison Shadow", "剧毒鬼魅"),
            [40] = ("Death Knight", "死神骑士"),
            [41] = ("Death Cow", "牛魔王"),
            [45] = ("Bahamut", "小巴哈姆特"),
            [46] = ("Vepar", "死亡美人鱼"),
            [47] = ("Valkyrie", "蓝翼海怪"),
            [48] = ("Lizard King", "巫师王"),
            [49] = ("Hydra", "海魔希特拉"),
            [51] = ("Great Bahamut", "大巴哈姆特"),
            [52] = ("Silver Valkyrie", "银弓海怪"),
            [57] = ("Iron Wheel", "铁轮战士"),
            [58] = ("Tantallos", "破坏骑士"),
            [59] = ("Zaikan", "魔王扎坎"),
            [60] = ("Bloody Wolf", "铁脊怪"),
            [61] = ("Beam Knight", "黑炎魔"),
            [62] = ("Mutant", "巨齿兽"),
            [63] = ("Death Beam Knight", "炽炎魔"),
            [69] = ("Alquamos", "阿卡摩斯"),
            [70] = ("Queen Rainer", "风后"),
            [71] = ("Mega Crust", "恶灵"),
            [72] = ("Phantom Knight", "幻影骑士"),
            [73] = ("Drakan", "蓝魔龙"),
            [74] = ("Alpha Crust", "恶灵王"),
            [75] = ("Great Drakan", "红魔龙"),
            [76] = ("Dark Phoenix Shield", "天魔菲尼斯（护盾阶段）"),
            [77] = ("Dark Phoenix", "天魔菲尼斯"),
            [144] = ("Death Angel 1", "死亡天使 1"),
            [145] = ("Death Centurion 1", "狂武士 1"),
            [146] = ("Blood Soldier 1", "龙虾守卫 1"),
            [147] = ("Aegis 1", "阿卡斯 1"),
            [148] = ("Rogue Centurion 1", "武士 1"),
            [149] = ("Necron 1", "暗黑巫师 1"),
            [152] = ("Gate to Kalima 1 of {0}", "{0}的卡利玛1入口"),
            [153] = ("Gate to Kalima 2 of {0}", "{0}的卡利玛2入口"),
            [154] = ("Gate to Kalima 3 of {0}", "{0}的卡利玛3入口"),
            [155] = ("Gate to Kalima 4 of {0}", "{0}的卡利玛4入口"),
            [156] = ("Gate to Kalima 5 of {0}", "{0}的卡利玛5入口"),
            [157] = ("Gate to Kalima 6 of {0}", "{0}的卡利玛6入口"),
            [158] = ("Gate to Kalima 7 of {0}", "{0}的卡利玛7入口"),
            [160] = ("Schriker 1", "暗黑傀儡 1"),
            [161] = ("Illusion of Kundun 1", "昆顿幻影 1"),
            [174] = ("Death Angel 2", "死亡天使 2"),
            [175] = ("Death Centurion 2", "狂武士 2"),
            [176] = ("Blood Soldier 2", "龙虾守卫 2"),
            [177] = ("Aegis 2", "阿卡斯 2"),
            [178] = ("Rogue Centurion 2", "武士 2"),
            [179] = ("Necron 2", "暗黑巫师 2"),
            [180] = ("Schriker 2", "暗黑傀儡 2"),
            [181] = ("Illusion of Kundun 2", "昆顿幻影 2"),
            [182] = ("Death Angel 3", "死亡天使 3"),
            [183] = ("Death Centurion 3", "狂武士 3"),
            [184] = ("Blood Soldier 3", "龙虾守卫 3"),
            [185] = ("Aegis 3", "阿卡斯 3"),
            [186] = ("Rogue Centurion 3", "武士 3"),
            [187] = ("Necron 3", "暗黑巫师 3"),
            [188] = ("Schriker 3", "暗黑傀儡 3"),
            [189] = ("Illusion of Kundun 3", "昆顿幻影 3"),
            [190] = ("Death Angel 4", "死亡天使 4"),
            [191] = ("Death Centurion 4", "狂武士 4"),
            [192] = ("Blood Soldier 4", "龙虾守卫 4"),
            [193] = ("Aegis 4", "阿卡斯 4"),
            [194] = ("Rogue Centurion 4", "武士 4"),
            [195] = ("Necron 4", "暗黑巫师 4"),
            [196] = ("Schriker 4", "暗黑傀儡 4"),
            [197] = ("Illusion of Kundun 4", "昆顿幻影 4"),
            [204] = ("Wolf Status", "神狼雕像"),
            [205] = ("Wolf Altar1", "神狼护台1"),
            [206] = ("Wolf Altar2", "神狼护台2"),
            [207] = ("Wolf Altar3", "神狼护台3"),
            [208] = ("Wolf Altar4", "神狼护台4"),
            [209] = ("Wolf Altar5", "神狼护台5"),
            [223] = ("Senior", "长老"),
            [224] = ("Guardsman", "攻城卫兵"),
            [226] = ("Pet Trainer", "驯兽师"),
            [229] = ("Marlon", "警卫队长摩伦"),
            [233] = ("Messenger of Arch.", "大天使的使者"),
            [235] = ("Sevina the Priestess", "圣导士塞维娜"),
            [237] = ("Charon", "卡隆"),
            [238] = ("Chaos Goblin", "玛雅哥布林"),
            [240] = ("Baz The Vault Keeper", "仓库使者赛佛特"),
            [241] = ("Guild Master", "战盟使者罗兰斯"),
            [256] = ("Lahap", "赛尔维斯"),
            [257] = ("Elf Soldier", "幻影导师"),
            [260] = ("Death Angel 5", "死亡天使 5"),
            [261] = ("Death Centurion 5", "狂武士 5"),
            [262] = ("Blood Soldier 5", "龙虾守卫 5"),
            [263] = ("Aegis 5", "阿卡斯 5"),
            [264] = ("Rogue Centurion 5", "武士 5"),
            [265] = ("Necron 5", "暗黑巫师 5"),
            [266] = ("Schriker 5", "暗黑傀儡 5"),
            [267] = ("Illusion of Kundun 5", "昆顿幻影 5"),
            [268] = ("Death Angel 6", "死亡天使 6"),
            [269] = ("Death Centurion 6", "狂武士 6"),
            [270] = ("Blood Soldier 6", "龙虾守卫 6"),
            [271] = ("Aegis 6", "阿卡斯 6"),
            [272] = ("Rogue Centurion 6", "武士 6"),
            [273] = ("Necron 6", "暗黑巫师 6"),
            [274] = ("Schriker 6", "暗黑傀儡 6"),
            [275] = ("Illusion of Kundun 7", "昆顿幻影 7"),
            [277] = ("Castle Gate1", "城门1"),
            [278] = ("Life Stone", "生命之石"),
            [283] = ("Guardian Statue", "守护石像"),
            [288] = ("Canon Tower", "巨弩发射器"),
            [290] = ("Lizard Warrior", "冷血变异者"),
            [291] = ("Fire Golem", "熔岩巨魔"),
            [292] = ("Queen Bee", "嗜血蜂后"),
            [293] = ("Poison Golem", "毒巨魔"),
            [294] = ("Axe Warrior", "巨斧战士"),
            [295] = ("Erohim", "炼狱魔王"),
            [304] = ("Witch Queen", "丛林女巫师"),
            [305] = ("Blue Golem", "丛林残暴者"),
            [306] = ("Death Rider", "丛林暗杀者"),
            [307] = ("Forest Orc", "丛林生命体"),
            [308] = ("Death Tree", "丛林树精灵"),
            [309] = ("Hell Maine", "丛林召唤者"),
            [310] = ("Hammer Scout", "刺锤侦察兵"),
            [311] = ("Lance Scout", "长矛侦察兵"),
            [312] = ("Bow Scout", "魔弓侦察兵"),
            [313] = ("Werewolf", "暗黑血狼人"),
            [314] = ("Scout(Hero)", "英雄侦察兵"),
            [315] = ("Werewolf(Hero)", "英雄血狼人"),
            [316] = ("Balram", "暗黑防御者"),
            [317] = ("Soram", "暗黑扫荡者"),
            [331] = ("Aegis 7", "阿卡斯 7"),
            [332] = ("Rogue Centurion 7", "武士 7"),
            [333] = ("Blood Soldier 7", "龙虾守卫 7"),
            [334] = ("Death Angel 7", "死亡天使 7"),
            [335] = ("Necron 7", "暗黑巫师 7"),
            [336] = ("Death Centurion 7", "狂武士 7"),
            [337] = ("Schriker 7", "暗黑傀儡 7"),
            [338] = ("Illusion of Kundun 6", "昆顿幻影 6"),
            [350] = ("Berserker", "疯魔"),
            [351] = ("Splinter Wolf", "裂角狼"),
            [352] = ("Iron Rider", "金甲兽"),
            [353] = ("Satyros", "半兽人"),
            [354] = ("Blade Hunter", "刀刃猎手"),
            [355] = ("Kentauros", "寒冰刺客"),
            [356] = ("Gigantis", "狂巨人"),
            [357] = ("Genocider", "屠杀者"),
            [358] = ("Persona", "假面巫"),
            [359] = ("Twin Tale", "毒步妖"),
            [360] = ("Dreadfear", "恐惧天使"),
            [361] = ("Nightmare", "咒怨魔王"),
            [362] = ("Maya (Hand Left)", "玛雅左手"),
            [363] = ("Maya (Hand Right)", "玛雅右手"),
            [364] = ("Maya", "玛雅"),
            [367] = ("Gateway Machine", "传送台"),
            [368] = ("Elphis", "艾尔菲丝"),
            [369] = ("Osbourne", "奥斯本"),
            [370] = ("Jerridon", "杰瑞敦"),
            [375] = ("Chaos Card Master", "玛雅使者"),
            [385] = ("Mirage", "弥拉邱"),
            [406] = ("Priest Devin", "弟子黛彬"),
            [407] = ("Werewolf Quarrel", "暗黑血狼人扩雷"),
            [409] = ("Balram (Trainee Soldier)", "暗黑防御者（训练兵）"),
            [410] = ("Death Spirit (Trainee Soldier)", "暗黑咒术师（训练兵）"),
            [411] = ("Soram (Trainee Soldier)", "暗黑扫荡者（训练兵）"),
            [412] = ("Dark Elf (Trainee Soldier)", "暗黑指挥官（训练兵）"),
            [418] = ("Strange Rabbit", "怪异的兔子"),
            [419] = ("Polluted Butterfly", "污染之蝶"),
            [420] = ("Hideous Rabbit", "疯狂的兔子"),
            [421] = ("Werewolf", "狼人"),
            [422] = ("Cursed Lich", "诅咒巫师"),
            [423] = ("Totem Golem", "图腾树人"),
            [424] = ("Grizzly", "灰熊"),
            [425] = ("Captain Grizzly", "残暴的灰熊"),
            [434] = ("Gigantis", "狂巨人"),
            [435] = ("Berserk", "疯魔"),
            [436] = ("Balram (Trainee)", "暗黑防御者（训练兵）"),
            [437] = ("Soram (Trainee)", "暗黑扫荡者（训练兵）"),
            [438] = ("Persona", "假面巫"),
            [439] = ("Dreadfear", "恐惧天使"),
            [440] = ("Dark_Elf", "暗黑指挥官"),
            [441] = ("Sapi-Unus", "树妖"),
            [442] = ("Sapi-Duo", "毒树妖"),
            [443] = ("Sapi-Tres", "残忍的树妖"),
            [444] = ("Shadow Pawn", "暗影爪牙"),
            [445] = ("Shadow Knight", "暗影骑士"),
            [446] = ("Shadow Look", "暗影武士"),
            [447] = ("Thunder Napin", "闪电巨人"),
            [448] = ("Ghost Napin", "幽灵巨人"),
            [449] = ("Blaze Napin", "寒冰巨人"),
            [452] = ("Seed Master", "萤之石管理员"),
            [453] = ("Seed Researcher", "萤之石研究员"),
            [454] = ("Ice Walker", "冰之魔犬"),
            [455] = ("Giant Mammoth", "冰之魔象"),
            [456] = ("Ice Giant", "冰之巨魔"),
            [457] = ("Coolutin", "冰之魔蛛"),
            [458] = ("Iron Knight", "冰铁剑魂"),
            [459] = ("Selupan", "冰霜巨蛛"),
            [480] = ("Zombie Fighter", "幽灵斗士"),
            [481] = ("Zombie Fighter", "幽灵斗士"),
            [482] = ("Resurrected Gladiator", "幽灵角斗士"),
            [483] = ("Resurrected Gladiator", "幽灵角斗士"),
            [484] = ("Ash Slaughterer", "幽灵屠杀者"),
            [485] = ("Ash Slaughterer", "幽灵屠杀者"),
            [486] = ("Blood Assassin", "幽灵暗杀者"),
            [487] = ("Cruel Blood Assassin", "幽灵残酷暗杀者"),
            [488] = ("Cruel Blood Assassin", "幽灵残酷暗杀者"),
            [489] = ("Burning Lava Giant", "幽灵巨人"),
            [490] = ("Ruthless Lava Giant", "幽灵残酷巨人"),
            [491] = ("Ruthless Lava Giant", "幽灵残酷巨人"),
            [492] = ("Moss The Merchant", "摩斯"),
            [522] = ("Adviser Jerinteu", "辅佐官杰林特"),
            [529] = ("Terrible Butcher", "愤怒的屠夫"),
            [530] = ("Mad Butcher", "屠夫"),
            [531] = ("Ice Walker", "冰之魔犬"),
            [532] = ("Larva", "毒虫（生魂广场）"),
            [534] = ("Doppelganger Elf", "生魂弓箭手"),
            [535] = ("Doppelganger Knight", "生魂剑士"),
            [536] = ("Doppelganger Wizard", "生魂魔法师"),
            [537] = ("Doppelganger Magic Gladiator", "生魂魔剑士"),
            [538] = ("Doppelganger Dark Lord", "生魂圣导师"),
            [539] = ("Doppelganger Summoner", "生魂召唤术师"),
            [540] = ("Lugard", "陆迦德"),
            [549] = ("Bloody Orc", "血腥丛林生命体"),
            [550] = ("Bloody Death Rider", "血腥丛林暗杀者"),
            [551] = ("Bloody Golem", "血腥丛林残暴者"),
            [552] = ("Bloody Witch Queen", "血腥丛林女巫师"),
            [553] = ("Berserker Warrior", "疯魔战士"),
            [554] = ("Kentauros Warrior", "寒冰刺客战士"),
            [555] = ("Gigantis Warrior", "狂巨人战士"),
            [556] = ("Genocider Warrior", "屠杀者战士"),
            [557] = ("Sapi Queen", "树妖女王"),
            [562] = ("Dark Mammoth", "黑暗冰之魔象"),
            [563] = ("Dark Giant", "黑暗冰之巨魔"),
            [564] = ("Dark Coolutin", "黑暗冰之魔蛛"),
            [565] = ("Dark Iron Knight", "黑暗冰铁剑魂"),
            [569] = ("Venomous Chain Scorpion", "剧毒勾尾蝎"),
            [570] = ("Bone Scorpion", "白骨勾尾蝎"),
            [571] = ("Orcus", "黑暗独角猿"),
            [572] = ("Gollock", "黑暗四臂猿"),
            [573] = ("Crypta", "金甲勇士"),
            [574] = ("Crypos", "黄蜂女王"),
            [575] = ("Condra", "幽灵石巨人"),
            [576] = ("Narcondra", "邪灵石巨人"),
            [579] = ("David", "戴彼得"),
        };

    /// <summary>
    /// Fills missing translations and replaces English copies of built-in monsters.
    /// </summary>
    /// <param name="configuration">The game configuration to update.</param>
    public static void AddMissingTranslations(GameConfiguration configuration)
    {
        foreach (var monster in configuration.Monsters)
        {
            if (!NamesByNumber.TryGetValue(monster.Number, out var names)
                || monster.Designation.ValueInNeutralLanguage != names.NeutralName)
            {
                continue;
            }

            var current = monster.Designation.GetTranslation(ChineseCulture, fallbackToNeutral: false);
            if (string.IsNullOrEmpty(current) || current == names.NeutralName)
            {
                monster.Designation = monster.Designation.WithTranslation(ChineseCulture, names.ChineseName);
            }
        }
    }
}
