// <copyright file="ChineseMonsterNames.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.Persistence.Initialization;

using System.Globalization;
using MUnique.OpenMU.DataModel.Configuration;

/// <summary>
/// Adds Simplified Chinese monster names while preserving customized translations.
/// </summary>
internal static class ChineseMonsterNames
{
    private static readonly CultureInfo Chinese = CultureInfo.GetCultureInfo("zh-CN");
    private static readonly IReadOnlyDictionary<short, (string Neutral, string Chinese, string Legacy)> Names =
        new Dictionary<short, (string Neutral, string Chinese, string Legacy)>
        {
            [0] = ("Bull Fighter", "牛怪", string.Empty),
            [1] = ("Hound", "猎犬怪", string.Empty),
            [2] = ("Budge Dragon", "幼龙", string.Empty),
            [3] = ("Spider", "蜘蛛", string.Empty),
            [4] = ("Elite Bull Fighter", "蛮牛怪", "精英Bull Fighter"),
            [5] = ("Hell Hound", "地狱猎犬怪", string.Empty),
            [6] = ("Lich", "黑巫师", string.Empty),
            [7] = ("Giant", "巨人", string.Empty),
            [8] = ("Poison Bull", "毒牛怪", "剧毒Bull"),
            [9] = ("Thunder Lich", "死灵巫师", string.Empty),
            [10] = ("Dark Knight", "暗黑骑士", "黑暗骑士"),
            [11] = ("Ghost", "幽灵", string.Empty),
            [12] = ("Larva", "毒虫", "幼虫"),
            [13] = ("Hell Spider", "地狱蜘蛛", string.Empty),
            [14] = ("Skeleton Warrior", "骷髅兵", "Skeleton 战士"),
            [15] = ("Skeleton Archer", "骷髅弓箭手", "Skeleton 弓箭手"),
            [16] = ("Elite Skeleton", "骷髅战士", "精英Skeleton"),
            [17] = ("Cyclops", "独眼巨人", string.Empty),
            [18] = ("Gorgon", "魔鬼戈登", string.Empty),
            [19] = ("Yeti", "雪人", string.Empty),
            [20] = ("Elite Yeti", "雪人王", "精英Yeti"),
            [21] = ("Assassin", "暗杀者", string.Empty),
            [22] = ("Ice Monster", "寒冰魔", string.Empty),
            [23] = ("Hommerd", "蓝魔怪", "霍默德"),
            [24] = ("Worm", "雪虫", string.Empty),
            [25] = ("Ice Queen", "冰后", "Ice 女王"),
            [26] = ("Goblin", "小哥布林", string.Empty),
            [27] = ("Chain Scorpion", "勾尾蝎", "链蝎"),
            [28] = ("Beetle Monster", "瓢虫怪", "甲虫怪"),
            [29] = ("Hunter", "偷猎者", "猎人"),
            [30] = ("Forest Monster", "树妖", "森林怪"),
            [31] = ("Agon", "亚昆", "阿贡"),
            [32] = ("Stone Golem", "石巨人", "Stone 石魔"),
            [33] = ("Elite Goblin", "大哥布林", "精英Goblin"),
            [34] = ("Cursed Wizard", "诅咒巫师", string.Empty),
            [35] = ("Death Gorgon", "死神戈登", string.Empty),
            [36] = ("Shadow", "鬼魅", string.Empty),
            [37] = ("Devil", "恶魔", string.Empty),
            [38] = ("Balrog", "魔王巴洛克", string.Empty),
            [39] = ("Poison Shadow", "剧毒鬼魅", "剧毒Shadow"),
            [40] = ("Death Knight", "死神骑士", "Death 骑士"),
            [41] = ("Death Cow", "牛魔王", string.Empty),
            [45] = ("Bahamut", "小巴哈姆特", string.Empty),
            [46] = ("Vepar", "死亡美人鱼", "维帕"),
            [47] = ("Valkyrie", "蓝翼海怪", string.Empty),
            [48] = ("Lizard King", "巫师王", string.Empty),
            [49] = ("Hydra", "海魔希特拉", string.Empty),
            [51] = ("Great Bahamut", "大巴哈姆特", "巨型巴哈姆特"),
            [52] = ("Silver Valkyrie", "银弓海怪", string.Empty),
            [57] = ("Iron Wheel", "铁轮战士", string.Empty),
            [58] = ("Tantallos", "破坏骑士", "坦塔罗斯"),
            [59] = ("Zaikan", "魔王扎坎", "扎伊坎"),
            [60] = ("Bloody Wolf", "铁脊怪", "血腥狼"),
            [61] = ("Beam Knight", "黑炎魔", "光束骑士"),
            [62] = ("Mutant", "巨齿兽", string.Empty),
            [63] = ("Death Beam Knight", "炽炎魔", "死亡光束骑士"),
            [69] = ("Alquamos", "阿卡摩斯", "阿尔夸莫斯"),
            [70] = ("Queen Rainer", "风后", "雷纳女王"),
            [71] = ("Mega Crust", "恶灵", "巨型甲壳兽"),
            [72] = ("Phantom Knight", "幻影骑士", "幻影骑士"),
            [73] = ("Drakan", "蓝魔龙", "德拉坎"),
            [74] = ("Alpha Crust", "恶灵王", "甲壳兽首领"),
            [75] = ("Great Drakan", "红魔龙", "巨型德拉坎"),
            [76] = ("Dark Phoenix Shield", "天魔菲尼斯（护盾阶段）", "黑暗Phoenix Shield"),
            [77] = ("Dark Phoenix", "天魔菲尼斯", "黑暗Phoenix"),
            [144] = ("Death Angel 1", "死亡天使 1", string.Empty),
            [145] = ("Death Centurion 1", "狂武士 1", string.Empty),
            [146] = ("Blood Soldier 1", "龙虾守卫 1", "Blood 士兵 1"),
            [147] = ("Aegis 1", "阿卡斯 1", string.Empty),
            [148] = ("Rogue Centurion 1", "武士 1", string.Empty),
            [149] = ("Necron 1", "暗黑巫师 1", string.Empty),
            [152] = ("Gate to Kalima 1 of {0}", "{0}的卡利玛1入口", "大门 to Kalima 1 的 {0}"),
            [153] = ("Gate to Kalima 2 of {0}", "{0}的卡利玛2入口", "大门 to Kalima 2 的 {0}"),
            [154] = ("Gate to Kalima 3 of {0}", "{0}的卡利玛3入口", "大门 to Kalima 3 的 {0}"),
            [155] = ("Gate to Kalima 4 of {0}", "{0}的卡利玛4入口", "大门 to Kalima 4 的 {0}"),
            [156] = ("Gate to Kalima 5 of {0}", "{0}的卡利玛5入口", "大门 to Kalima 5 的 {0}"),
            [157] = ("Gate to Kalima 6 of {0}", "{0}的卡利玛6入口", "大门 to Kalima 6 的 {0}"),
            [158] = ("Gate to Kalima 7 of {0}", "{0}的卡利玛7入口", "大门 to Kalima 7 的 {0}"),
            [160] = ("Schriker 1", "暗黑傀儡 1", string.Empty),
            [161] = ("Illusion of Kundun 1", "昆顿幻影 1", "Illusion 的 Kundun 1"),
            [174] = ("Death Angel 2", "死亡天使 2", string.Empty),
            [175] = ("Death Centurion 2", "狂武士 2", string.Empty),
            [176] = ("Blood Soldier 2", "龙虾守卫 2", "Blood 士兵 2"),
            [177] = ("Aegis 2", "阿卡斯 2", string.Empty),
            [178] = ("Rogue Centurion 2", "武士 2", string.Empty),
            [179] = ("Necron 2", "暗黑巫师 2", string.Empty),
            [180] = ("Schriker 2", "暗黑傀儡 2", string.Empty),
            [181] = ("Illusion of Kundun 2", "昆顿幻影 2", "Illusion 的 Kundun 2"),
            [182] = ("Death Angel 3", "死亡天使 3", string.Empty),
            [183] = ("Death Centurion 3", "狂武士 3", string.Empty),
            [184] = ("Blood Soldier 3", "龙虾守卫 3", "Blood 士兵 3"),
            [185] = ("Aegis 3", "阿卡斯 3", string.Empty),
            [186] = ("Rogue Centurion 3", "武士 3", string.Empty),
            [187] = ("Necron 3", "暗黑巫师 3", string.Empty),
            [188] = ("Schriker 3", "暗黑傀儡 3", string.Empty),
            [189] = ("Illusion of Kundun 3", "昆顿幻影 3", "Illusion 的 Kundun 3"),
            [190] = ("Death Angel 4", "死亡天使 4", string.Empty),
            [191] = ("Death Centurion 4", "狂武士 4", string.Empty),
            [192] = ("Blood Soldier 4", "龙虾守卫 4", "Blood 士兵 4"),
            [193] = ("Aegis 4", "阿卡斯 4", string.Empty),
            [194] = ("Rogue Centurion 4", "武士 4", string.Empty),
            [195] = ("Necron 4", "暗黑巫师 4", string.Empty),
            [196] = ("Schriker 4", "暗黑傀儡 4", string.Empty),
            [197] = ("Illusion of Kundun 4", "昆顿幻影 4", "Illusion 的 Kundun 4"),
            [204] = ("Wolf Status", "神狼雕像", "狼图腾"),
            [205] = ("Wolf Altar1", "神狼护台1", "狼祭坛1"),
            [206] = ("Wolf Altar2", "神狼护台2", "狼祭坛2"),
            [207] = ("Wolf Altar3", "神狼护台3", "狼祭坛3"),
            [208] = ("Wolf Altar4", "神狼护台4", "狼祭坛4"),
            [209] = ("Wolf Altar5", "神狼护台5", "狼祭坛5"),
            [223] = ("Senior", "长老", "城堡长老"),
            [224] = ("Guardsman", "攻城卫兵", "卫兵"),
            [226] = ("Pet Trainer", "驯兽师", string.Empty),
            [229] = ("Marlon", "警卫队长摩伦", string.Empty),
            [233] = ("Messenger of Arch.", "大天使的使者", "大天使使者"),
            [235] = ("Sevina the Priestess", "圣导士塞维娜", "女祭司塞维娜"),
            [237] = ("Charon", "卡隆", string.Empty),
            [238] = ("Chaos Goblin", "玛雅哥布林", string.Empty),
            [240] = ("Baz The Vault Keeper", "仓库使者赛佛特", "仓库管理员巴兹"),
            [241] = ("Guild Master", "战盟使者罗兰斯", "公会会长"),
            [256] = ("Lahap", "赛尔维斯", string.Empty),
            [257] = ("Elf Soldier", "幻影导师", "Elf 士兵"),
            [260] = ("Death Angel 5", "死亡天使 5", string.Empty),
            [261] = ("Death Centurion 5", "狂武士 5", string.Empty),
            [262] = ("Blood Soldier 5", "龙虾守卫 5", "Blood 士兵 5"),
            [263] = ("Aegis 5", "阿卡斯 5", string.Empty),
            [264] = ("Rogue Centurion 5", "武士 5", string.Empty),
            [265] = ("Necron 5", "暗黑巫师 5", string.Empty),
            [266] = ("Schriker 5", "暗黑傀儡 5", string.Empty),
            [267] = ("Illusion of Kundun 5", "昆顿幻影 5", "Illusion 的 Kundun 5"),
            [268] = ("Death Angel 6", "死亡天使 6", string.Empty),
            [269] = ("Death Centurion 6", "狂武士 6", string.Empty),
            [270] = ("Blood Soldier 6", "龙虾守卫 6", "Blood 士兵 6"),
            [271] = ("Aegis 6", "阿卡斯 6", string.Empty),
            [272] = ("Rogue Centurion 6", "武士 6", string.Empty),
            [273] = ("Necron 6", "暗黑巫师 6", string.Empty),
            [274] = ("Schriker 6", "暗黑傀儡 6", string.Empty),
            [275] = ("Illusion of Kundun 7", "昆顿幻影 7", "Illusion 的 Kundun 7"),
            [277] = ("Castle Gate1", "城门1", "Castle 大门1"),
            [278] = ("Life Stone", "生命之石", "生命之石"),
            [283] = ("Guardian Statue", "守护石像", "守卫ian 雕像"),
            [288] = ("Canon Tower", "巨弩发射器", "弩炮塔"),
            [290] = ("Lizard Warrior", "冷血变异者", "蜥蜴战士"),
            [291] = ("Fire Golem", "熔岩巨魔", "火焰石魔"),
            [292] = ("Queen Bee", "嗜血蜂后", "蜂后"),
            [293] = ("Poison Golem", "毒巨魔", "剧毒石魔"),
            [294] = ("Axe Warrior", "巨斧战士", "斧战士"),
            [295] = ("Erohim", "炼狱魔王", "艾罗希姆"),
            [304] = ("Witch Queen", "丛林女巫师", "女巫王"),
            [305] = ("Blue Golem", "丛林残暴者", "蓝色石魔"),
            [306] = ("Death Rider", "丛林暗杀者", "死亡骑士"),
            [307] = ("Forest Orc", "丛林生命体", "森林兽人"),
            [308] = ("Death Tree", "丛林树精灵", "死亡之树"),
            [309] = ("Hell Maine", "丛林召唤者", "地狱犬王"),
            [310] = ("Hammer Scout", "刺锤侦察兵", "锤兵斥候"),
            [311] = ("Lance Scout", "长矛侦察兵", "长枪斥候"),
            [312] = ("Bow Scout", "魔弓侦察兵", "弓兵斥候"),
            [313] = ("Werewolf", "暗黑血狼人", "狼人"),
            [314] = ("Scout(Hero)", "英雄侦察兵", string.Empty),
            [315] = ("Werewolf(Hero)", "英雄血狼人", "Were狼(Hero)"),
            [316] = ("Balram", "暗黑防御者", "巴拉姆"),
            [317] = ("Soram", "暗黑扫荡者", "索拉姆"),
            [331] = ("Aegis 7", "阿卡斯 7", string.Empty),
            [332] = ("Rogue Centurion 7", "武士 7", string.Empty),
            [333] = ("Blood Soldier 7", "龙虾守卫 7", "Blood 士兵 7"),
            [334] = ("Death Angel 7", "死亡天使 7", string.Empty),
            [335] = ("Necron 7", "暗黑巫师 7", string.Empty),
            [336] = ("Death Centurion 7", "狂武士 7", string.Empty),
            [337] = ("Schriker 7", "暗黑傀儡 7", string.Empty),
            [338] = ("Illusion of Kundun 6", "昆顿幻影 6", "Illusion 的 Kundun 6"),
            [350] = ("Berserker", "疯魔", string.Empty),
            [351] = ("Splinter Wolf", "裂角狼", "Splinter 狼"),
            [352] = ("Iron Rider", "金甲兽", string.Empty),
            [353] = ("Satyros", "半兽人", "萨提罗斯"),
            [354] = ("Blade Hunter", "刀刃猎手", "利刃猎手"),
            [355] = ("Kentauros", "寒冰刺客", "半人马"),
            [356] = ("Gigantis", "狂巨人", "巨人"),
            [357] = ("Genocider", "屠杀者", "屠杀者"),
            [358] = ("Persona", "假面巫", "佩尔索纳"),
            [359] = ("Twin Tale", "毒步妖", "双尾兽"),
            [360] = ("Dreadfear", "恐惧天使", "恐惧魔王"),
            [361] = ("Nightmare", "咒怨魔王", string.Empty),
            [362] = ("Maya (Hand Left)", "玛雅左手", string.Empty),
            [363] = ("Maya (Hand Right)", "玛雅右手", string.Empty),
            [364] = ("Maya", "玛雅", string.Empty),
            [367] = ("Gateway Machine", "传送台", "大门way Machine"),
            [368] = ("Elphis", "艾尔菲丝", "艾尔菲丝"),
            [369] = ("Osbourne", "奥斯本", "奥斯本"),
            [370] = ("Jerridon", "杰瑞敦", "杰里顿"),
            [375] = ("Chaos Card Master", "玛雅使者", string.Empty),
            [385] = ("Mirage", "弥拉邱", "幻影"),
            [406] = ("Priest Devin", "弟子黛彬", "牧师德文"),
            [407] = ("Werewolf Quarrel", "暗黑血狼人扩雷", "Were狼 Quarrel"),
            [409] = ("Balram (Trainee Soldier)", "暗黑防御者（训练兵）", "Balram (Trainee 士兵)"),
            [410] = ("Death Spirit (Trainee Soldier)", "暗黑咒术师（训练兵）", "Death 精灵 (Trainee 士兵)"),
            [411] = ("Soram (Trainee Soldier)", "暗黑扫荡者（训练兵）", "Soram (Trainee 士兵)"),
            [412] = ("Dark Elf (Trainee Soldier)", "暗黑指挥官（训练兵）", "黑暗Elf (Trainee 士兵)"),
            [418] = ("Strange Rabbit", "怪异的兔子", "Strange 兔子"),
            [419] = ("Polluted Butterfly", "污染之蝶", "污染蝴蝶"),
            [420] = ("Hideous Rabbit", "疯狂的兔子", "丑陋兔子"),
            [421] = ("Werewolf", "狼人", "狼人"),
            [422] = ("Cursed Lich", "诅咒巫师", "诅咒巫师"),
            [423] = ("Totem Golem", "图腾树人", "图腾石魔"),
            [424] = ("Grizzly", "灰熊", "灰熊"),
            [425] = ("Captain Grizzly", "残暴的灰熊", "灰熊队长"),
            [434] = ("Gigantis", "狂巨人", "巨人"),
            [435] = ("Berserk", "疯魔", "狂暴者"),
            [436] = ("Balram (Trainee)", "暗黑防御者（训练兵）", string.Empty),
            [437] = ("Soram (Trainee)", "暗黑扫荡者（训练兵）", string.Empty),
            [438] = ("Persona", "假面巫", "佩尔索纳"),
            [439] = ("Dreadfear", "恐惧天使", "恐惧魔王"),
            [440] = ("Dark_Elf", "暗黑指挥官", "暗精灵"),
            [441] = ("Sapi-Unus", "树妖", string.Empty),
            [442] = ("Sapi-Duo", "毒树妖", string.Empty),
            [443] = ("Sapi-Tres", "残忍的树妖", string.Empty),
            [444] = ("Shadow Pawn", "暗影爪牙", "暗影兵卒"),
            [445] = ("Shadow Knight", "暗影骑士", "暗影骑士"),
            [446] = ("Shadow Look", "暗影武士", "暗影侦察者"),
            [447] = ("Thunder Napin", "闪电巨人", "雷纳平"),
            [448] = ("Ghost Napin", "幽灵巨人", "幽灵纳平"),
            [449] = ("Blaze Napin", "寒冰巨人", "烈焰纳平"),
            [452] = ("Seed Master", "萤之石管理员", "种子大师"),
            [453] = ("Seed Researcher", "萤之石研究员", "种子研究员"),
            [454] = ("Ice Walker", "冰之魔犬", "冰行者"),
            [455] = ("Giant Mammoth", "冰之魔象", "巨型猛犸"),
            [456] = ("Ice Giant", "冰之巨魔", "冰巨人"),
            [457] = ("Coolutin", "冰之魔蛛", "库鲁丁"),
            [458] = ("Iron Knight", "冰铁剑魂", "铁甲骑士"),
            [459] = ("Selupan", "冰霜巨蛛", "塞尔潘"),
            [480] = ("Zombie Fighter", "幽灵斗士", "僵尸斗士"),
            [481] = ("Zombie Fighter", "幽灵斗士", "僵尸斗士"),
            [482] = ("Resurrected Gladiator", "幽灵角斗士", "复活角斗士"),
            [483] = ("Resurrected Gladiator", "幽灵角斗士", "复活角斗士"),
            [484] = ("Ash Slaughterer", "幽灵屠杀者", "灰烬屠夫"),
            [485] = ("Ash Slaughterer", "幽灵屠杀者", "灰烬屠夫"),
            [486] = ("Blood Assassin", "幽灵暗杀者", "血刺客"),
            [487] = ("Cruel Blood Assassin", "幽灵残酷暗杀者", "残酷血刺客"),
            [488] = ("Cruel Blood Assassin", "幽灵残酷暗杀者", "残酷血刺客"),
            [489] = ("Burning Lava Giant", "幽灵巨人", "燃烧熔岩巨人"),
            [490] = ("Ruthless Lava Giant", "幽灵残酷巨人", "无情熔岩巨人"),
            [491] = ("Ruthless Lava Giant", "幽灵残酷巨人", "无情熔岩巨人"),
            [492] = ("Moss The Merchant", "摩斯", string.Empty),
            [522] = ("Adviser Jerinteu", "辅佐官杰林特", "顾问杰林特"),
            [529] = ("Terrible Butcher", "愤怒的屠夫", string.Empty),
            [530] = ("Mad Butcher", "屠夫", string.Empty),
            [531] = ("Ice Walker", "冰之魔犬", string.Empty),
            [532] = ("Larva", "毒虫（生魂广场）", string.Empty),
            [534] = ("Doppelganger Elf", "生魂弓箭手", string.Empty),
            [535] = ("Doppelganger Knight", "生魂剑士", string.Empty),
            [536] = ("Doppelganger Wizard", "生魂魔法师", string.Empty),
            [537] = ("Doppelganger Magic Gladiator", "生魂魔剑士", string.Empty),
            [538] = ("Doppelganger Dark Lord", "生魂圣导师", string.Empty),
            [539] = ("Doppelganger Summoner", "生魂召唤术师", string.Empty),
            [540] = ("Lugard", "陆迦德", string.Empty),
            [549] = ("Bloody Orc", "血腥丛林生命体", "血腥Orc"),
            [550] = ("Bloody Death Rider", "血腥丛林暗杀者", "血腥Death Rider"),
            [551] = ("Bloody Golem", "血腥丛林残暴者", "血腥石魔"),
            [552] = ("Bloody Witch Queen", "血腥丛林女巫师", "血腥Witch 女王"),
            [553] = ("Berserker Warrior", "疯魔战士", "Berserker 战士"),
            [554] = ("Kentauros Warrior", "寒冰刺客战士", "Kentauros 战士"),
            [555] = ("Gigantis Warrior", "狂巨人战士", "Gigantis 战士"),
            [556] = ("Genocider Warrior", "屠杀者战士", "Genocider 战士"),
            [557] = ("Sapi Queen", "树妖女王", "Sapi 女王"),
            [562] = ("Dark Mammoth", "黑暗冰之魔象", "黑暗Mammoth"),
            [563] = ("Dark Giant", "黑暗冰之巨魔", "黑暗Giant"),
            [564] = ("Dark Coolutin", "黑暗冰之魔蛛", "黑暗Coolutin"),
            [565] = ("Dark Iron Knight", "黑暗冰铁剑魂", "黑暗Iron 骑士"),
            [569] = ("Venomous Chain Scorpion", "剧毒勾尾蝎", string.Empty),
            [570] = ("Bone Scorpion", "白骨勾尾蝎", string.Empty),
            [571] = ("Orcus", "黑暗独角猿", string.Empty),
            [572] = ("Gollock", "黑暗四臂猿", string.Empty),
            [573] = ("Crypta", "金甲勇士", string.Empty),
            [574] = ("Crypos", "黄蜂女王", string.Empty),
            [575] = ("Condra", "幽灵石巨人", string.Empty),
            [576] = ("Narcondra", "邪灵石巨人", string.Empty),
            [579] = ("David", "戴彼得", "大卫"),
        };

    /// <summary>
    /// Fills missing translations and corrects known legacy translations of built-in monsters.
    /// </summary>
    /// <param name="configuration">The game configuration to update.</param>
    public static void Apply(GameConfiguration configuration)
    {
        foreach (var monster in configuration.Monsters)
        {
            if (!Names.TryGetValue(monster.Number, out var names)
                || monster.Designation.ValueInNeutralLanguage != names.Neutral)
            {
                continue;
            }

            var current = monster.Designation.GetTranslation(Chinese, fallbackToNeutral: false);
            if (current != names.Chinese
                && (string.IsNullOrEmpty(current) || current == names.Legacy || current == names.Neutral))
            {
                monster.Designation = monster.Designation.WithTranslation(Chinese, names.Chinese);
            }
        }
    }
}
