// <copyright file="GeneratePersistentTypeRegistryAttribute.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.Persistence;

/// <summary>
/// Requests the generation of a <see cref="IPersistentTypeRegistry"/> for the persistent types of an assembly,
/// which are the classes of the specified namespace.
/// The registry is generated by the <c>PersistentTypeRegistryGenerator</c> of the <c>MUnique.OpenMU.Persistence.Generators</c> project.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class GeneratePersistentTypeRegistryAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GeneratePersistentTypeRegistryAttribute"/> class.
    /// </summary>
    /// <param name="namespace">The namespace of the persistent types.</param>
    public GeneratePersistentTypeRegistryAttribute(string @namespace)
    {
        this.Namespace = @namespace;
    }

    /// <summary>
    /// Gets the namespace of the persistent types.
    /// </summary>
    public string Namespace { get; }
}
