//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Network.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUnique.OpenMU.Network.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP is detected automatically by considering the environment. No parameter required..
        /// </summary>
        public static string IpResolverType_Auto_Description {
            get {
                return ResourceManager.GetString("IpResolverType_Auto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string IpResolverType_Auto_Name {
            get {
                return ResourceManager.GetString("IpResolverType_Auto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP or a host name can be set manually. Use this, if the other options don&apos;t work for you..
        /// </summary>
        public static string IpResolverType_Custom_Description {
            get {
                return ResourceManager.GetString("IpResolverType_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string IpResolverType_Custom_Name {
            get {
                return ResourceManager.GetString("IpResolverType_Custom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP is detected by asking the DNS about the IP of the own host name. The first IP is used. No parameter required. Use this, if you want to use the server within a local LAN, e.g. at home..
        /// </summary>
        public static string IpResolverType_Local_Description {
            get {
                return ResourceManager.GetString("IpResolverType_Local_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string IpResolverType_Local_Name {
            get {
                return ResourceManager.GetString("IpResolverType_Local_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP is resolved as &apos;127.127.127.127&apos;. No parameter required. Use this, if you want to use the server and client just within your own computer, e.g. during development..
        /// </summary>
        public static string IpResolverType_Loopback_Description {
            get {
                return ResourceManager.GetString("IpResolverType_Loopback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loopback.
        /// </summary>
        public static string IpResolverType_Loopback_Name {
            get {
                return ResourceManager.GetString("IpResolverType_Loopback_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP is detected by asking an external service (https://www.ipify.org/) about the own IP. No parameter required. Use this, when the server is running on a server and should be reachable from the internet. Firewall is required to be opened for the ports of game, connect and chat servers..
        /// </summary>
        public static string IpResolverType_Public_Description {
            get {
                return ResourceManager.GetString("IpResolverType_Public_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string IpResolverType_Public_Name {
            get {
                return ResourceManager.GetString("IpResolverType_Public_Name", resourceCulture);
            }
        }
    }
}
