version: '3.4'

services:
  database:
    ports:
      - "5433:5432"
  loki:
    ports:
      - "3100:3100"
  prometheus:
    ports:
      - "9000:9090"
      
  redis-state:
    ports:
      - "6379:6379"
  
  gameServer0:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "81:8080"

  gameServer1:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "82:8080"

  connectServer:
    build:
      context: ../../src
      dockerfile: Dapr/ConnectServer.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  loginServer:
    build:
      context: ../../src
      dockerfile: Dapr/LoginServer.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  friendServer:
    build:
      context: ../../src
      dockerfile: Dapr/FriendServer.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  guildServer:
    build:
      context: ../../src
      dockerfile: Dapr/GuildServer.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  chatServer:
    build:
      context: ../../src
      dockerfile: Dapr/ChatServer.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  adminPanel:
    build:
      context: ../../src
      dockerfile: Dapr/AdminPanel.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "88:8080"