// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using MUnique.OpenMU.DataModel.Configuration;
using MUnique.OpenMU.Persistence.EntityFramework.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.CompiledModels.ForEntityDataContext
{
    [EntityFrameworkInternal]
    public partial class CastleSiegeUpgradeDefinitionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition",
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition),
                baseEntityType,
                propertyCount: 10,
                foreignKeyCount: 5,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueGeneratorFactory: new MUnique.OpenMU.Persistence.EntityFramework.GuidV7ValueGeneratorFactory().Create,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var castleSiegeConfigurationId = runtimeEntityType.AddProperty(
                "CastleSiegeConfigurationId",
                typeof(Guid?),
                nullable: true);
            castleSiegeConfigurationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var castleSiegeConfigurationId1 = runtimeEntityType.AddProperty(
                "CastleSiegeConfigurationId1",
                typeof(Guid?),
                nullable: true);
            castleSiegeConfigurationId1.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var castleSiegeConfigurationId2 = runtimeEntityType.AddProperty(
                "CastleSiegeConfigurationId2",
                typeof(Guid?),
                nullable: true);
            castleSiegeConfigurationId2.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var castleSiegeConfigurationId3 = runtimeEntityType.AddProperty(
                "CastleSiegeConfigurationId3",
                typeof(Guid?),
                nullable: true);
            castleSiegeConfigurationId3.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var castleSiegeConfigurationId4 = runtimeEntityType.AddProperty(
                "CastleSiegeConfigurationId4",
                typeof(Guid?),
                nullable: true);
            castleSiegeConfigurationId4.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var level = runtimeEntityType.AddProperty(
                "Level",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetProperty("Level", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetField("<Level>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            level.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var requiredJewelOfGuardianCount = runtimeEntityType.AddProperty(
                "RequiredJewelOfGuardianCount",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetProperty("RequiredJewelOfGuardianCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetField("<RequiredJewelOfGuardianCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            requiredJewelOfGuardianCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var requiredZen = runtimeEntityType.AddProperty(
                "RequiredZen",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetProperty("RequiredZen", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetField("<RequiredZen>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            requiredZen.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.CastleSiegeUpgradeDefinition).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            value.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { castleSiegeConfigurationId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { castleSiegeConfigurationId1 });

            var index1 = runtimeEntityType.AddIndex(
                new[] { castleSiegeConfigurationId2 });

            var index2 = runtimeEntityType.AddIndex(
                new[] { castleSiegeConfigurationId3 });

            var index3 = runtimeEntityType.AddIndex(
                new[] { castleSiegeConfigurationId4 });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CastleSiegeConfigurationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawGateDefenseUpgrades = principalEntityType.AddNavigation("RawGateDefenseUpgrades",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetProperty("RawGateDefenseUpgrades", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetField("<RawGateDefenseUpgrades>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CastleSiegeConfigurationId1") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawGateLifeUpgrades = principalEntityType.AddNavigation("RawGateLifeUpgrades",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetProperty("RawGateLifeUpgrades", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetField("<RawGateLifeUpgrades>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_CastleSiegeUpgradeDefinition_CastleSiegeConfiguration_Cast~1");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CastleSiegeConfigurationId2") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawStatueDefenseUpgrades = principalEntityType.AddNavigation("RawStatueDefenseUpgrades",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetProperty("RawStatueDefenseUpgrades", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetField("<RawStatueDefenseUpgrades>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_CastleSiegeUpgradeDefinition_CastleSiegeConfiguration_Cast~2");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CastleSiegeConfigurationId3") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawStatueLifeUpgrades = principalEntityType.AddNavigation("RawStatueLifeUpgrades",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetProperty("RawStatueLifeUpgrades", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetField("<RawStatueLifeUpgrades>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_CastleSiegeUpgradeDefinition_CastleSiegeConfiguration_Cast~3");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CastleSiegeConfigurationId4") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawStatueRegenUpgrades = principalEntityType.AddNavigation("RawStatueRegenUpgrades",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeUpgradeDefinition>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetProperty("RawStatueRegenUpgrades", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CastleSiegeConfiguration).GetField("<RawStatueRegenUpgrades>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_CastleSiegeUpgradeDefinition_CastleSiegeConfiguration_Cast~4");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "config");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CastleSiegeUpgradeDefinition");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
