// <auto-generated />
using System;
using System.Reflection;
using MUnique.OpenMU.DataModel.Configuration;
using MUnique.OpenMU.Persistence.EntityFramework.Model;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.CompiledModels.ForEntityDataContext
{
    [EntityFrameworkInternal]
    public partial class ConnectServerDefinitionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MUnique.OpenMU.Persistence.EntityFramework.Model.ConnectServerDefinition",
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.ConnectServerDefinition),
                baseEntityType,
                propertyCount: 17,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueGeneratorFactory: new MUnique.OpenMU.Persistence.EntityFramework.GuidV7ValueGeneratorFactory().Create,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var checkMaxConnectionsPerAddress = runtimeEntityType.AddProperty(
                "CheckMaxConnectionsPerAddress",
                typeof(bool),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("CheckMaxConnectionsPerAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<CheckMaxConnectionsPerAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            checkMaxConnectionsPerAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var clientId = runtimeEntityType.AddProperty(
                "ClientId",
                typeof(Guid?),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.ConnectServerDefinition).GetProperty("ClientId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.ConnectServerDefinition).GetField("<ClientId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            clientId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var clientListenerPort = runtimeEntityType.AddProperty(
                "ClientListenerPort",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("ClientListenerPort", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<ClientListenerPort>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            clientListenerPort.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var currentPatchVersion = runtimeEntityType.AddProperty(
                "CurrentPatchVersion",
                typeof(byte[]),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("CurrentPatchVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<CurrentPatchVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            currentPatchVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var disconnectOnUnknownPacket = runtimeEntityType.AddProperty(
                "DisconnectOnUnknownPacket",
                typeof(bool),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("DisconnectOnUnknownPacket", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<DisconnectOnUnknownPacket>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            disconnectOnUnknownPacket.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var listenerBacklog = runtimeEntityType.AddProperty(
                "ListenerBacklog",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("ListenerBacklog", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<ListenerBacklog>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            listenerBacklog.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxConnections = runtimeEntityType.AddProperty(
                "MaxConnections",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaxConnections", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaxConnections>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxConnections.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxConnectionsPerAddress = runtimeEntityType.AddProperty(
                "MaxConnectionsPerAddress",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaxConnectionsPerAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaxConnectionsPerAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxConnectionsPerAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxFtpRequests = runtimeEntityType.AddProperty(
                "MaxFtpRequests",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaxFtpRequests", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaxFtpRequests>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxFtpRequests.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxIpRequests = runtimeEntityType.AddProperty(
                "MaxIpRequests",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaxIpRequests", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaxIpRequests>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxIpRequests.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxServerListRequests = runtimeEntityType.AddProperty(
                "MaxServerListRequests",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaxServerListRequests", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaxServerListRequests>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxServerListRequests.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maximumReceiveSize = runtimeEntityType.AddProperty(
                "MaximumReceiveSize",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("MaximumReceiveSize", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<MaximumReceiveSize>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            maximumReceiveSize.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var patchAddress = runtimeEntityType.AddProperty(
                "PatchAddress",
                typeof(string),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("PatchAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<PatchAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            patchAddress.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var serverId = runtimeEntityType.AddProperty(
                "ServerId",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("ServerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<ServerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            serverId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var timeout = runtimeEntityType.AddProperty(
                "Timeout",
                typeof(TimeSpan),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetProperty("Timeout", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ConnectServerDefinition).GetField("<Timeout>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new TimeSpan(0, 0, 0, 0, 0));
            timeout.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { clientId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClientId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            var rawClient = declaringEntityType.AddNavigation("RawClient",
                runtimeForeignKey,
                onDependent: true,
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.GameClientDefinition),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.ConnectServerDefinition).GetProperty("RawClient", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "config");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ConnectServerDefinition");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
