// <auto-generated />
using System;
using System.Reflection;
using MUnique.OpenMU.DataModel.Configuration.ItemCrafting;
using MUnique.OpenMU.Persistence.EntityFramework.Model;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.CompiledModels.ForEntityDataContext
{
    [EntityFrameworkInternal]
    public partial class SimpleCraftingSettingsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MUnique.OpenMU.Persistence.EntityFramework.Model.SimpleCraftingSettings",
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.SimpleCraftingSettings),
                baseEntityType,
                propertyCount: 17,
                navigationCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.SimpleCraftingSettings).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.SimpleCraftingSettings).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueGeneratorFactory: new MUnique.OpenMU.Persistence.EntityFramework.GuidV7ValueGeneratorFactory().Create,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maximumSuccessPercent = runtimeEntityType.AddProperty(
                "MaximumSuccessPercent",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("MaximumSuccessPercent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<MaximumSuccessPercent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            maximumSuccessPercent.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var money = runtimeEntityType.AddProperty(
                "Money",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("Money", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<Money>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            money.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var moneyPerFinalSuccessPercentage = runtimeEntityType.AddProperty(
                "MoneyPerFinalSuccessPercentage",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("MoneyPerFinalSuccessPercentage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<MoneyPerFinalSuccessPercentage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            moneyPerFinalSuccessPercentage.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var multipleAllowed = runtimeEntityType.AddProperty(
                "MultipleAllowed",
                typeof(bool),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("MultipleAllowed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<MultipleAllowed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            multipleAllowed.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var npcPriceDivisor = runtimeEntityType.AddProperty(
                "NpcPriceDivisor",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("NpcPriceDivisor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<NpcPriceDivisor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            npcPriceDivisor.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var resultItemExcellentOptionChance = runtimeEntityType.AddProperty(
                "ResultItemExcellentOptionChance",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("ResultItemExcellentOptionChance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<ResultItemExcellentOptionChance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            resultItemExcellentOptionChance.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var resultItemLuckOptionChance = runtimeEntityType.AddProperty(
                "ResultItemLuckOptionChance",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("ResultItemLuckOptionChance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<ResultItemLuckOptionChance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            resultItemLuckOptionChance.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var resultItemMaxExcOptionCount = runtimeEntityType.AddProperty(
                "ResultItemMaxExcOptionCount",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("ResultItemMaxExcOptionCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<ResultItemMaxExcOptionCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            resultItemMaxExcOptionCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var resultItemSelect = runtimeEntityType.AddProperty(
                "ResultItemSelect",
                typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.ResultItemSelection),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("ResultItemSelect", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<ResultItemSelect>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            resultItemSelect.SetSentinelFromProviderValue(0);
            resultItemSelect.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var resultItemSkillChance = runtimeEntityType.AddProperty(
                "ResultItemSkillChance",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("ResultItemSkillChance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<ResultItemSkillChance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            resultItemSkillChance.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercent = runtimeEntityType.AddProperty(
                "SuccessPercent",
                typeof(byte),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            successPercent.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercentageAdditionForAncientItem = runtimeEntityType.AddProperty(
                "SuccessPercentageAdditionForAncientItem",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercentageAdditionForAncientItem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercentageAdditionForAncientItem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            successPercentageAdditionForAncientItem.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercentageAdditionForExcellentItem = runtimeEntityType.AddProperty(
                "SuccessPercentageAdditionForExcellentItem",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercentageAdditionForExcellentItem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercentageAdditionForExcellentItem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            successPercentageAdditionForExcellentItem.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercentageAdditionForGuardianItem = runtimeEntityType.AddProperty(
                "SuccessPercentageAdditionForGuardianItem",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercentageAdditionForGuardianItem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercentageAdditionForGuardianItem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            successPercentageAdditionForGuardianItem.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercentageAdditionForLuck = runtimeEntityType.AddProperty(
                "SuccessPercentageAdditionForLuck",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercentageAdditionForLuck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercentageAdditionForLuck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            successPercentageAdditionForLuck.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var successPercentageAdditionForSocketItem = runtimeEntityType.AddProperty(
                "SuccessPercentageAdditionForSocketItem",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetProperty("SuccessPercentageAdditionForSocketItem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Configuration.ItemCrafting.SimpleCraftingSettings).GetField("<SuccessPercentageAdditionForSocketItem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            successPercentageAdditionForSocketItem.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "config");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SimpleCraftingSettings");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
