// <auto-generated />
using System;
using System.Reflection;
using MUnique.OpenMU.Persistence.EntityFramework.Model;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.CompiledModels.ForTradeContext
{
    [EntityFrameworkInternal]
    public partial class MasterSkillDefinitionSkillEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill",
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill),
                baseEntityType,
                propertyCount: 2,
                keyCount: 1);

            var masterSkillDefinitionId = runtimeEntityType.AddProperty(
                "MasterSkillDefinitionId",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill).GetProperty("MasterSkillDefinitionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill).GetField("<MasterSkillDefinitionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            masterSkillDefinitionId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var skillId = runtimeEntityType.AddProperty(
                "SkillId",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill).GetProperty("SkillId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.MasterSkillDefinitionSkill).GetField("<SkillId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            skillId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { masterSkillDefinitionId, skillId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "config");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MasterSkillDefinitionSkill");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
