// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using MUnique.OpenMU.DataModel.Entities;
using MUnique.OpenMU.Persistence.EntityFramework.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.CompiledModels.ForTradeContext
{
    [EntityFrameworkInternal]
    public partial class QuestMonsterKillRequirementStateEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState",
                typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueGeneratorFactory: new MUnique.OpenMU.Persistence.EntityFramework.GuidV7ValueGeneratorFactory().Create,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var characterQuestStateId = runtimeEntityType.AddProperty(
                "CharacterQuestStateId",
                typeof(Guid?),
                nullable: true);
            characterQuestStateId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var killCount = runtimeEntityType.AddProperty(
                "KillCount",
                typeof(int),
                propertyInfo: typeof(MUnique.OpenMU.DataModel.Entities.QuestMonsterKillRequirementState).GetProperty("KillCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.DataModel.Entities.QuestMonsterKillRequirementState).GetField("<KillCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            killCount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var requirementId = runtimeEntityType.AddProperty(
                "RequirementId",
                typeof(Guid?),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState).GetProperty("RequirementId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState).GetField("<RequirementId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            requirementId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { characterQuestStateId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CharacterQuestStateId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade);

            var rawRequirementStates = principalEntityType.AddNavigation("RawRequirementStates",
                runtimeForeignKey,
                onDependent: false,
                typeof(System.Collections.Generic.ICollection<MUnique.OpenMU.Persistence.EntityFramework.Model.QuestMonsterKillRequirementState>),
                propertyInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CharacterQuestState).GetProperty("RawRequirementStates", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MUnique.OpenMU.Persistence.EntityFramework.Model.CharacterQuestState).GetField("<RawRequirementStates>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "data");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "QuestMonsterKillRequirementState");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
