// <copyright file="JewelMix.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="JewelMix"/>.
/// </summary>
public partial class JewelMix : MUnique.OpenMU.DataModel.Configuration.JewelMix, IIdentifiable, IConvertibleTo<JewelMix>
{
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets the raw object of <see cref="SingleJewel" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("singleJewel")]
    public ItemDefinition RawSingleJewel
    {
        get => base.SingleJewel as ItemDefinition;
        set => base.SingleJewel = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Configuration.Items.ItemDefinition SingleJewel
    {
        get => base.SingleJewel;
        set => base.SingleJewel = value;
    }

    /// <summary>
    /// Gets the raw object of <see cref="MixedJewel" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("mixedJewel")]
    public ItemDefinition RawMixedJewel
    {
        get => base.MixedJewel as ItemDefinition;
        set => base.MixedJewel = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Configuration.Items.ItemDefinition MixedJewel
    {
        get => base.MixedJewel;
        set => base.MixedJewel = value;
    }

    /// <inheritdoc />
    public override MUnique.OpenMU.DataModel.Configuration.JewelMix Clone(MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        var clone = new JewelMix();
        clone.AssignValuesOf(this, gameConfiguration);
        return clone;
    }
    
    /// <inheritdoc />
    public override void AssignValuesOf(MUnique.OpenMU.DataModel.Configuration.JewelMix other, MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        base.AssignValuesOf(other, gameConfiguration);
        this.Id = other.GetId();
    }

    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public JewelMix Convert() => this;
}
